### ISSUE TITLE
detectObject causes crash on windows 32bit

### ISSUE THREAD

**Issue by dongbat** [peterbraden/node-opencv#100]
I installed opencv and node-opencv on windows and try to run the first example

```javascript
cv.readImage("./examples/test.jpg", function(err, im){
  im.detectObject(cv.FACE_CASCADE, {}, function(err, faces){
    for (var i=0;i<faces.length; i++){
      var x = faces[i]
      im.ellipse(x.x + x.width/2, x.y + x.height/2, x.width/2, x.height/2);
    }
    im.save('./out.jpg');
  });
})
```
The process exit without any error message. 
(At first I think just the callback is not being called. But when I try to run a http server, the server stops too)
.
I tried some other examples (like examples/contours.js), they work just fine.

**Comment by Naikno** [comment]
Same problem here, 
there is a fix?

**Comment by danschultzer** [comment]
Works as expected here. Is "./examples/test.jpg" a correct path?

@Naikno can you post the code you try to run?
