### ISSUE TITLE
Create colored matrix or fill matrix with color

### ISSUE THREAD

**Issue by xFragger** [peterbraden/node-opencv#102]
I'm implementing some kind of thumbnail creation with differing aspect ratios and need the possibility to copy a matrix (source) to another (bigger) matrix (target).
The Target should be colored before this step, so i don't have to create colored lines for letterboxing.

I hope i will find the time to give you the needed changes in Matrix.cc/.h, so you would just have to merge and publish it.

**Comment by danschultzer** [comment]
This is possible:

```javascript
var im = new cv.Matrix(100, 100, cv.Constants.CV_8UC3, [0, 255, 0]);
im.save("result.jpg");
```
