### ISSUE TITLE
copyTo does not work as i think it should

### ISSUE THREAD

**Issue by xFragger** [peterbraden/node-opencv#103]
I guess, if i copy one matrix into a ROI of another matrix via source.copyTo(target, x, y), the target image should have the source image at the given position.

```
var target = new cv.Matrix(100, 100),
      source = {a Matrix, read from a 50x50 image}
;
source.copyTo(target, 25, 25);
target.save(filename);
```
The result should be the source image in the center of a black image (black borders, 25px thick), but the result is a black image with some colored pixels on it.

**Comment by danschultzer** [comment]
You need to add channels, like this:

```javascript
var cv = require("opencv");
cv.readImage('image.jpg', function(err, img){
  var target = new cv.Matrix(100, 100, cv.Constants.CV_8UC3),
    source = img.crop(0,0,50,50);
  source.copyTo(target, 25, 25);
  target.save("result.jpg");
});
