### ISSUE TITLE
Installin node-opencv on Ubuntu and OpenCV 2.4.0

### ISSUE THREAD

**Issue by viktorstaikov** [peterbraden/node-opencv#105]
Hi,

I have installed OpenCV following this blogpost http://karytech.blogspot.com/2012/05/opencv-24-on-ubuntu-1204.html

After adding the module to package.json and running NPM INSTALL I get the following error:

**gyp http GET http://nodejs.org/dist/v0.10.25/node-v0.10.25.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.25/node-v0.10.25.tar.gz
make: Entering directory `/home/ubuntu/imageresizing/node_modules/opencv/build'
  CXX(target) Release/obj.target/opencv/src/init.o
  CXX(target) Release/obj.target/opencv/src/Matrix.o
/home/ubuntu/imageresizing/node_modules/opencv/.node-gyp/0.10.25/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> Matrix::New(const v8::Arguments&)’:
/home/ubuntu/imageresizing/node_modules/opencv/.node-gyp/0.10.25/deps/v8/include/v8.h:209:48: warning: ‘mat’ may be used uninitialized in this function [-Wuninitialized]
../src/Matrix.cc:104:10: note: ‘mat’ was declared here
  CXX(target) Release/obj.target/opencv/src/OpenCV.o
  CXX(target) Release/obj.target/opencv/src/CascadeClassifierWrap.o
  CXX(target) Release/obj.target/opencv/src/Contours.o
  CXX(target) Release/obj.target/opencv/src/Point.o
  CXX(target) Release/obj.target/opencv/src/VideoCaptureWrap.o
  CXX(target) Release/obj.target/opencv/src/CamShift.o
  CXX(target) Release/obj.target/opencv/src/HighGUI.o
/home/ubuntu/imageresizing/node_modules/opencv/.node-gyp/0.10.25/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> NamedWindow::New(const v8::Arguments&)’:
/home/ubuntu/imageresizing/node_modules/opencv/.node-gyp/0.10.25/deps/v8/include/v8.h:209:48: warning: ‘win’ may be used uninitialized in this function [-Wuninitialized]
../src/HighGUI.cc:35:16: note: ‘win’ was declared here
  CXX(target) Release/obj.target/opencv/src/FaceRecognizer.o
../src/FaceRecognizer.cc: In static member function ‘static v8::Handle<v8::Value> FaceRecognizerWrap::New(const v8::Arguments&)’:
../src/FaceRecognizer.cc:64:80: error: too many arguments to function ‘cv::Ptr<cv::FaceRecognizer> cv::createLBPHFaceRecognizer(int, int, int, int)’
/usr/local/include/opencv2/contrib/contrib.hpp:951:36: note: declared here
../src/FaceRecognizer.cc: In static member function ‘static v8::Handle<v8::Value> FaceRecognizerWrap::CreateLBPH(const v8::Arguments&)’:
../src/FaceRecognizer.cc:91:3: error: too many arguments to function ‘cv::Ptr<cv::FaceRecognizer> cv::createLBPHFaceRecognizer(int, int, int, int)’
/usr/local/include/opencv2/contrib/contrib.hpp:951:36: note: declared here
../src/FaceRecognizer.cc: In static member function ‘static v8::Handle<v8::Value> FaceRecognizerWrap::CreateEigen(const v8::Arguments&)’:
../src/FaceRecognizer.cc:112:3: error: too many arguments to function ‘cv::Ptr<cv::FaceRecognizer> cv::createEigenFaceRecognizer(int)’
/usr/local/include/opencv2/contrib/contrib.hpp:949:36: note: declared here
../src/FaceRecognizer.cc: In static member function ‘static v8::Handle<v8::Value> FaceRecognizerWrap::CreateFisher(const v8::Arguments&)’:
../src/FaceRecognizer.cc:133:3: error: too many arguments to function ‘cv::Ptr<cv::FaceRecognizer> cv::createFisherFaceRecognizer(int)’
/usr/local/include/opencv2/contrib/contrib.hpp:950:36: note: declared here
../src/FaceRecognizer.cc: In static member function ‘static v8::Handle<v8::Value> FaceRecognizerWrap::UpdateSync(const v8::Arguments&)’:
../src/FaceRecognizer.cc:218:14: error: ‘class cv::FaceRecognizer’ has no member named ‘update’
../src/FaceRecognizer.cc: In static member function ‘static v8::Handle<v8::Value> FaceRecognizerWrap::PredictSync(const v8::Arguments&)’:
../src/FaceRecognizer.cc:234:52: error: no matching function for call to ‘cv::FaceRecognizer::predict(cv::Mat&, int&, double&)’
../src/FaceRecognizer.cc:234:52: note: candidate is:
/usr/local/include/opencv2/contrib/contrib.hpp:931:21: note: virtual int cv::FaceRecognizer::predict(cv::InputArray) const
/usr/local/include/opencv2/contrib/contrib.hpp:931:21: note:   candidate expects 1 argument, 3 provided
../src/FaceRecognizer.cc: In static member function ‘static v8::Handle<v8::Value> FaceRecognizerWrap::GetMat(const v8::Arguments&)’:
../src/FaceRecognizer.cc:273:26: error: ‘class cv::FaceRecognizer’ has no member named ‘getMat’
make: *** [Release/obj.target/opencv/src/FaceRecognizer.o] Error 1
make: Leaving directory `/home/ubuntu/imageresizing/node_modules/opencv/build'**

Can you help me resolve this issue because it's blocking for me?

**Comment by danschultzer** [comment]
Sounds like this has been resolved with upgrade to OpenCV 2.4.9, and the commit in https://github.com/peterbraden/node-opencv/commit/cbaff9a1336393c35cad3502d36e37e4333a70ed preventing the issue from happening again. I'll close this for now.
