### ISSUE TITLE
OpenCV.h:9:16: fatal error: cv.h: No such file or director

### ISSUE THREAD

**Issue by majimboo** [peterbraden/node-opencv#110]
> opencv@0.4.0 preinstall /home/travis/build/majimboo/thumborizer/node_modules/opencv
> node-gyp clean rebuild
make: Entering directory `/home/travis/build/majimboo/thumborizer/node_modules/opencv/build'
  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:1:0:
../src/OpenCV.h:9:16: fatal error: cv.h: No such file or directory

**Comment by danschultzer** [comment]
@kennethklee :+1:
