### ISSUE TITLE
Installation on mac is failing

### ISSUE THREAD

**Issue by deez21** [peterbraden/node-opencv#117]
When I try to install node-opencv on my mac it fails with this code (see image below).
I have node v0.10.26 and node-gyp v0.12.2 installed.

![screen shot 2014-04-05 at 12 21 40](https://cloud.githubusercontent.com/assets/3679307/2622489/856524a4-bcb4-11e3-8c36-d257d4688bbf.png)

**Comment by SlightlyCyborg** [comment]
I've heard that downgrading nodejs fixes this: I've tried 4 versions of node. 0.10.22 does not work for me

**Comment by Glavin001** [comment]
This resolved the `ld: library not found for -llibtbb.dylib` issue for me: http://stackoverflow.com/a/23582975/2578205 

>Suppose libtbb.dylib is in /usr/local/lib/libtbb.dylib and opencv.pc is in /usr/local/lib/pkgconfig (The location may vary depending on where you install tbb and pkg-config)
>
>Then edit /usr/local/lib/pkgconfig/opencv.pc, change -llibtbb.dylib to /usr/local/lib/libtbb.dylib

**Comment by danschultzer** [comment]
@Glavin001 has the actual solution for the `libtbb.dylib` library error. I believe `brew install tbb` might do the trick too. I'll close this for now.
