### ISSUE TITLE
dyld: lazy symbol binding failed

### ISSUE THREAD

**Issue by mooglin** [peterbraden/node-opencv#133]
This happens anytime I try to run one of the examples. In my own attempts I can create a `cv.VideoStream(0)` but once I try to create an object detection stream or read from the camera it throws the same error.

```
[~/opencvtest/node_modules/opencv/examples] node camera

dyld: lazy symbol binding failed: Symbol not found: __ZN2cv7imwriteERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS_11_InputArrayERKNS0_6vectorIiNS4_IiEEEE
  Referenced from: /Users/moog/opencvtest/node_modules/opencv/build/Release/opencv.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2cv7imwriteERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS_11_InputArrayERKNS0_6vectorIiNS4_IiEEEE
  Referenced from: /Users/moog/opencvtest/node_modules/opencv/build/Release/opencv.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```

I've tried reinstalling OpenCV and rebuilding but I hit the same error. 
```
opencv: v2.4.9
node.js: v0.10.28
node-opencv: 0.5.0
osx: 10.8.4
```
Thanks for any insight.

**Comment by danschultzer** [comment]
This seems to answer the issue: http://stackoverflow.com/a/27334789/939535

> `Library Search Paths` tells linker where to search for the library to link to. But when the executable is run, the library may be searched by dynamic loader (`dyld`) in different places. This is controlled by 'Install Name' of the library that may be queried by `otool -D libFoo.dylib`.
> 
> So, for example, if the library you are linking to is in `/bar/libFoo.dylib`, but its install name is `/baz/libFoo.dylib`, you need to put `/bar` in `Library Search Paths`, but when you run the binary it'll be searched in `/baz`.
> 
> You can also find out where the libraries are seachred when the executable is run by `otool -L <executable>`.
> 
> If the path to shared library is not absolute, dynamic loader tries to load it from some standard paths. If you set `DYLD_PRINT_LIBRARIES` environment variable, `dyld` will log the filenames of the libraries it tries to load to `stderr`. You can override the paths where `dyld` searches for libraries by setting `DYLD_LIBRARY_PATH` variable (`:`-separated list of paths).
> 
> More info about `dyld` environment variables can be found in `man dyld`.
