### ISSUE TITLE
Throw errors when run "node-gyp clean rebuild"

### ISSUE THREAD

**Issue by haohcraft** [peterbraden/node-opencv#139]
I installed opencv 2.4.9 under os 10.9

When I ran "node-gyp clean build", it threw some errors.

Any idea???
----------------
haos-mbp-2:node-opencv Hao$ node-gyp clean rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@0.13.1
gyp info using node@0.10.28 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/Users/Hao/.nvm/v0.10.28/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Hao/Documents/Study/OnlineCourse/WebDev/Projects/opencv/node-opencv/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Hao/.nvm/v0.10.28/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Hao/.node-gyp/0.10.28/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Hao/.node-gyp/0.10.28',
gyp info spawn args   '-Dmodule_root_dir=/Users/Hao/Documents/WebDev/Projects/opencv/node-opencv',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/opencv/src/init.o
c++: error: unrecognized command line option ‘-stdlib=libc++’
make: *** [Release/obj.target/opencv/src/init.o] Error 1

**Comment by danschultzer** [comment]
Sounds like you need to install `clang`. I assume this issue is no longer relevant, so I'll close it.
