### ISSUE TITLE
Extracting Submatrix

### ISSUE THREAD

**Issue by hpx7** [peterbraden/node-opencv#150]
It is often useful while using OpenCV to be able to extract a subimage from an image. What I would like to be able to do is something like this:

    cv.readImage('foo.jpg', function (err, im) {
        var x, y, w, h = ... // the position and dimensions of the desired subimage
        var subimage = im.submatrix(x, y, w, h); // how to get this functionality?
        subimage.save('crop.jpg');
    });

In the python OpenCV bindings, one can simply do this:

    subimage = im[y:y+h, x:x+w]

There there a way to achieve this in the current state of this library?

**Comment by danschultzer** [comment]
This has been resolved with #157, just use `image.crop(x,y,width,height)`.
