### ISSUE TITLE
car_detection.js example broken

### ISSUE THREAD

**Issue by BradThater** [peterbraden/node-opencv#180]
car_detection.js example when implemented returns 0 cars on any of the example car pictures (https://raw.githubusercontent.com/peterbraden/node-opencv/master/examples/car1.jpg) (https://raw.githubusercontent.com/peterbraden/node-opencv/master/examples/car2.jpg). The cars object remains empty as the detectObject function calls back with 0.

This requires revision.

**Comment by danschultzer** [comment]
I guess this has been resolved.
