### ISSUE TITLE
Building for node-webkit

### ISSUE THREAD

**Issue by cupofnestor** [peterbraden/node-opencv#192]
I cannot successfully build node-opencv using nw-gyp for use in a node-webkit application.  The error is:
```
dlopen(/node_modules/opencv/build/Release/opencv.node, 1): Symbol not found: __ZTVN2cv11_InputArrayE
```
It seems that node-opencv cannot find the proper .dylib
I have installed opencv 2.4.9 via homebrew, and the libs are properly linked in opencv.target.mk

See [This issue](https://github.com/rogerwang/node-webkit/issues/1867) on node-webkit.

**Comment by dasantonym** [comment]
nw-gyp didn't work for me, too. i am building successfully with
```
node-pre-gyp rebuild --runtime=node-webkit --target=0.12.0
```

**Comment by peterbraden** [comment]
Did this work? Please re-open if not.
