### ISSUE TITLE
Simple Shape

### ISSUE THREAD

**Issue by huei90** [peterbraden/node-opencv#197]
How do I simply detect shape (circle, triangle, rect) in image using node-opencv

**Comment by bradrisse** [comment]
The first part of detecting shapes is located here /examples/detect-shapes.js. Using the corner count, you will be able to determine if its a circle (0 corners), triangle (3 corners), or rectangle (4 corners). To determine if its a square or rectangle you will need to first determine its a rectangle with 4 corners and then determine the height and width and compare.
