### ISSUE TITLE
Simple Motion Detection

### ISSUE THREAD

**Issue by timkendall** [peterbraden/node-opencv#205]
I'm just getting into this library now but it would be nice to have a simple method to detect motion from a video stream. Something like this would be nice:

```javascript
var video = new cv.VideoCapture(0); // Camera stream or from file
video.StartTrackMotion({ 
  threshold: 75, // Ignore certain degree of difference
  differentiate: true // Tries to differentiate between motion, so we don't get a continuous stream of motion events
});

video.on('motion', function (motion) {
  motion.time // => [Date Object]
  motion.location // => [Contour Object]
});

video.StopTrackMotion();
```

In the mean time what would be the best way of going about this with the current library?

**Comment by bradrisse** [comment]
The simple method isnt available, but if you implement something like this https://blog.cedric.ws/opencv-simple-motion-detection by comparing the current frame with the previous frame you could create a method using this method.
