### ISSUE TITLE
Running on Cygwin

### ISSUE THREAD

**Issue by Assrock** [peterbraden/node-opencv#206]
Hi,
I have built a Webapplication on Ubuntu with NodeJs, opencv and the node-opencv module.
But now I must run it on a Windows machine. I think using Cygwin is the best way to handle the problem, but can you guys explain me how I can install opencv on Cygwin, that work with the node-opencv module?

I installed the cygwinports opencv-lib, but that doestn work for me. Everytime I want to start the application, I got an error that the include files doesnt exist.

hope you can help me

**Comment by danschultzer** [comment]
I'll close this since it's more than 2 years old, but please reply with log output if you still experience issues.
