### ISSUE TITLE
Template matching demo

### ISSUE THREAD

**Issue by edi9999** [peterbraden/node-opencv#208]
I can't find any documentation on how to use template matching . do you have a demo or an api?

**Comment by tlear** [comment]
Did you get anywhere with this?  I'm looking for something similar and it would be really helpful.

**Comment by edi9999** [comment]
Nope, sorry. I decided to write that part in C++ directly

**Comment by oskardahlberg** [comment]
I wrote a method to make it more manageable, hope this makes any sense
https://gist.github.com/oskardahlberg/a9bfd1916d923b765631

**Comment by danschultzer** [comment]
This discussion is moved to https://github.com/peterbraden/node-opencv/issues/387
