### ISSUE TITLE
Can no longer build opencv package

### ISSUE THREAD

**Issue by metalaureate** [peterbraden/node-opencv#210]
All of a sudden and for now reason I can identify, node install opencv fails with this error:

```
In file included from ../src/Matrix.cc:1:
In file included from ../src/Contours.h:1:
In file included from ../src/OpenCV.h:12:
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:184:10: error: call to 'New' is ambiguous
  return NanIntern::Factory<T>::New(arg0);
```

Here's the full build complaint: http://pastebin.com/mKK5ELrJ

This has just started to happen (as of about 12pm PST), on Mac and Ubuntu.

This is in the nan module, which was updated today:

nan                   Native Abstractions for Node.js: C++ header for Node 0.8->0.12 compatibility =rvagg =kkoopa 2015-01-14 19:39  1.5.0

I will log a bug there. I don't know what to do in situations like this, so any help would be much appreciated.

**Comment by metalaureate** [comment]
From Nan response:

"The error comes from trying to make a v8::Integer from a long unsigned int. V8 does not support 64-bit integers. You need to downcast to 32 bit. Previously this may have happened implicitly, which was not really proper.

If long is not 64 bit in this case, the problem is likely on our end and needs a small fix."

**Comment by AndriMar** [comment]
I had the same problem.
What I did was install the 1.3.0 version of nan and then install the opencv.

**Comment by metalaureate** [comment]
Thanks. Yeah, I forked opencv and changed the nan version.
