### ISSUE TITLE
Invalid ELF header using docker node-opencv image

### ISSUE THREAD

**Issue by metalaureate** [peterbraden/node-opencv#211]
I'm using this docker image `siomiz/node-opencv:latest`
 
After running `npm install opencv` wirth nan changed to ~1.4.1, and trying to run the demo face detect script, I get the error:
```
opencv_1   | events.js:72
opencv_1   |         throw er; // Unhandled 'error' event
opencv_1   |               ^
opencv_1   | Error: /usr/local/src/opencv/node_modules/opencv/build/Release/opencv.node: invalid ELF header
```
I have no idea what it means or how to resolve it. Any help would be really appreciated.

**Comment by danschultzer** [comment]
The library has been compiled to different architecture. Try with `opencv@5.0.0`, as it builds with a specific package name that includes arch to prevent this issue.
