### ISSUE TITLE
Error in installing node open cv in Mac

### ISSUE THREAD

**Issue by esconone** [peterbraden/node-opencv#214]
Can you please help me with the installation of node opencv in Mac 10.10.1?

Current opencv installed: 2.4.9

When I try to install opencv I get errors which is given below:

$ npm install
npm http GET https://registry.npmjs.org/opencv
npm http 304 https://registry.npmjs.org/opencv
npm http GET https://registry.npmjs.org/buffers
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/buffers
npm http 304 https://registry.npmjs.org/nan

> opencv@1.0.0 install /Users/person/http/opencv/node_modules/opencv
> node-gyp rebuild

  CXX(target) Release/obj.target/opencv/src/init.o
  CXX(target) Release/obj.target/opencv/src/Matrix.o
../src/Matrix.cc:1273:22: warning: address of stack memory associated with local
      variable 'ret' returned [-Wreturn-stack-address]
        return (cv::Rect*) &ret;
                            ^~~
In file included from ../src/Matrix.cc:1:
In file included from ../src/Contours.h:1:
In file included from ../src/OpenCV.h:12:
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:184:10: error: call to 'New' is ambiguous
  return NanIntern::Factory<T>::New(arg0);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/Matrix.cc:453:51: note: in instantiation of function template
      specialization 'NanNew<v8::Integer, unsigned long>' requested here
        v8::Handle<v8::Value> constructorArgs[3] = {buf, NanNew<v8::Inte...
                                                         ^
../node_modules/nan/nan_new.h:86:26: note: candidate function
  static inline return_t New(int32_t value);
                         ^
../node_modules/nan/nan_new.h:87:26: note: candidate function
  static inline return_t New(uint32_t value);
                         ^
1 warning and 1 error generated.
make: *** [Release/obj.target/opencv/src/Matrix.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/person/http/opencv/node_modules/opencv
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! opencv@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@1.0.0 install script.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/person/http/opencv
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/person/http/opencv/npm-debug.log
npm ERR! not ok code 0

**Comment by bobmoff** [comment]
I have the same problem

**Comment by tlear** [comment]
I also have the same problem

**Comment by bobmoff** [comment]
There is a fix: https://github.com/peterbraden/node-opencv/issues/213

**Comment by peterbraden** [comment]
Fixed by #218
