### ISSUE TITLE
Updated Documentation?

### ISSUE THREAD

**Issue by tlear** [peterbraden/node-opencv#216]
So I know this would be a fairly big undertaking, but is there any chance of getting an updated documentation to detail all of the various methods that have since been added to the API?  Examples include better details on things like canny, hough transforms, matchTemplate, etc.

**Comment by danschultzer** [comment]
Since this is just a bindings library, I think it's better to just check the [OpenCV API](http://docs.opencv.org) ([the python api documentation](http://docs.opencv.org/2.4/modules/refman.html) being easier to translate to js).
