### ISSUE TITLE
Launching the main demo and other questions

### ISSUE THREAD

**Issue by lezabour** [peterbraden/node-opencv#219]
Hi,

First, thanks for your code and explaination!!
I was looking for something like that, and what you've done seems very cool ;)

But i still have problem running your code, very basic problem ;)

I'm a beginner at node.js, use it with rapsberry pi, and want to add opencv like you did for face detection / recognition.

Anyway, i have install your code, everything is good, but after it, don't know what to launch.
I have done  "npm start"  but after few seconds, nothing happens and goes back to command line (no server is up)

In the main directory, i see the index.html with your video player, but i don't have the xxx.js to run the server. 
When i go to /examples/, i can launch some (face-detection from monalisa picture etc...), others are throwing exception, but didn't find the one that match your demo. (have the video stream in browser and face detection , and possibility to take pictures)

Can you tell me what i have to do once i have install everything to run the server as you did in your video?

Thank you very much!

**Comment by danschultzer** [comment]
I assume this issue is no longer relevant, considering that it's more than year old. I'll reopen if you still have problem getting it to run.
