### ISSUE TITLE
[Question] How to use HoughCircles ?

### ISSUE THREAD

**Issue by Evoliofly** [peterbraden/node-opencv#226]
First of all, sorry if this is the wrong place to ask questions.

HoughCircles has been supported for a while now [(1)](https://github.com/peterbraden/node-opencv/commit/23fc1c04edcf6fa20a090a8d6d7c7dd25288ee0c), but as there's no real doc, I don't understand how to use it.

I know it isn't very difficult, but as I'm quite new to node-opencv and to opencv, I have no clue how to do it.

Could someone post an example ?

Thank you. :)

**Comment by Queuecumber** [comment]
Basically you want to load the image using `cv.imload` and then call the `houghCircles` method. You can refer to [this python tutoral](http://www.pyimagesearch.com/2014/07/21/detecting-circles-images-using-opencv-hough-circles/) for an explanation of the parameters. The code will look roughly like this

    cv.imload('test.jpg', function (mat)
    {
        var circles = mat.houghCircles(1.2, 100); // Probably going to need to change the params to suit your needs

        var firstCircleCenterX = circles[0][0];
        var firstCircleCenterY = circles[0][1];
        var firstCircleRadius = circles[0][2];

        // Do something with the circles
    }

Note that this code is untested and might not work

**Comment by Evoliofly** [comment]
Thank you, that's working well ! :)
