### ISSUE TITLE
install fail with io.js@1.2.0 via nvm on macOS 10.10.1

### ISSUE THREAD

**Issue by clonn** [peterbraden/node-opencv#227]
fail message is below,

```
m/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v43-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.0.0
npm ERR! argv "/Users/$USER/.nvm/versions/io.js/v1.2.0/bin/iojs" "/Users/$USER/.nvm/versions/io.js/v1.2.0/bin/npm" "install" "opencv"
npm ERR! node v1.2.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@3.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.
```

**Comment by alamcordeiro** [comment]
I had the same problem

Cloning repository and running node-pre-gyp install --fallback-to-build into folder
return this error:

```sheel
node-pre-gyp http 403 status code downloading tarball https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz (falling back to source compile with node-gyp) 
```
probably host binary  https://node-opencv.s3.amazonaws.com is down

**Comment by SlightlyCyborg** [comment]
Ditto to this. Mac Yosemite

<pre><code>
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/collinbell/.nvm/versions/node/v0.12.0/bin/node" "/Users/collinbell/.nvm/versions/node/v0.12.0/bin/npm" "install" "opencv"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@3.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
</code></pre>

**Comment by SlightlyCyborg** [comment]
try <code>brew install cmake</code>. It fixed everything for me. If that doesn't work, uninstall opencv and install using brew with the --32-bit flag

**Comment by clonn** [comment]
@SlightlyCyborg  thanks your solution, but it does not work for me.

every runs are broken in examples code.

**Comment by danschultzer** [comment]
@clonn do you still experience this issue with `opencv@5.0.0`?

**Comment by clonn** [comment]
this issus can be closed now, thanks @danschultzer
