### ISSUE TITLE
Specify encoding format on toBuffer

### ISSUE THREAD

**Issue by contra** [peterbraden/node-opencv#23]
Right now it seems like it's hardcoded to JPG

**Comment by danschultzer** [comment]
It's possible to change the encoding format in opencv@5.0.0:

https://github.com/peterbraden/node-opencv/blob/13a1de4f9259b5e745021f3198a8339ac99edecd/src/Matrix.cc#L614-L619

```
  // img.toBuffer({ext: ".png", pngCompression: 9}); // default png compression is 3
  // img.toBuffer({ext: ".jpg", jpegQuality: 80});
  // img.toBuffer(); // creates Jpeg with quality of 95 (Opencv default quality)
```
