### ISSUE TITLE
Unexpected result from "set" function

### ISSUE THREAD

**Issue by i-liszt** [peterbraden/node-opencv#242]
Hi, I try to use "set" function to modify pixels of an image; however, the result is so strange. The image becomes whole black. The following code is an example. The expected result should be a binary image. Do I misunderstand the set function? Thanks!

```javascript
var cv = require('opencv');

cv.readImage("./sample_1.jpg", function(err, img) {
	if (err) {
		console.log(err);
		return;
	} else {
		var height = img.height(), 
			width = img.width(),
			mat = new cv.Matrix(height, width);

		mat = img.copy();
		mat.convertGrayscale();
		
		for (var i = 0; i < height; i++) {
			for (var j = 0; j < width; j++) {
				if (mat.pixel(i, j) < 150) {
					mat.set(i, j, 0);
				} else {
					mat.set(i, j, 255);
				}
			}	
		}
		mat.save("./out.jpg");
	}
});
```

**Comment by paulovsm** [comment]
I'm facing the same issue here. @i-liszt Did figure out how to solve it?

In some circumstance another error happens: Segmentation fault (core dumped).

**Comment by paulovsm** [comment]
@i-liszt I found out that "pixel" method do what you need correctly, I tested here and it works smoothly. The method has two behaviors based on the number of arguments: with two arguments it behavior as "getter" but with three arguments it behavior as "setter".

**Comment by danschultzer** [comment]
I guess @paulovsm's comment is sufficient. I'll close this.
