### ISSUE TITLE
Upgrading nan to 1.7

### ISSUE THREAD

**Issue by AVVS** [peterbraden/node-opencv#243]
Any chance NaN will be upgraded? #223 will be fixed, along with a few nasty crashes on mac os.
Current version makes callback to be called twice and results in a segfault for certain images

**Comment by AVVS** [comment]
Fixed in #202

**Comment by wangxd8** [comment]
I put the resources in your node-opencv, into my project, but will still be reported "#<Object> has no method'ImageSimilarity'Object"... You know what the reason may be? It has been done for a day.
