### ISSUE TITLE
Error installing on Intel Galileo Gen 1

### ISSUE THREAD

**Issue by AdamMiltonBarker** [peterbraden/node-opencv#249]
root@quark00a8ee:~# date 042310452015
Thu Apr 23 10:45:00 UTC 2015
root@quark00a8ee:~# npm install opencv
npm http GET https://registry.npmjs.org/opencv
npm http 200 https://registry.npmjs.org/opencv
npm http GET https://registry.npmjs.org/opencv/-/opencv-3.0.0.tgz
npm http 200 https://registry.npmjs.org/opencv/-/opencv-3.0.0.tgz
npm http GET https://registry.npmjs.org/node-pre-gyp
npm http GET https://registry.npmjs.org/buffers
npm http GET https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/buffers
npm http 200 https://registry.npmjs.org/node-pre-gyp
npm http GET https://registry.npmjs.org/buffers/-/buffers-0.1.1.tgz
npm http 200 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.5.31.tgz
npm http GET https://registry.npmjs.org/nan/-/nan-1.4.3.tgz
npm http 200 https://registry.npmjs.org/buffers/-/buffers-0.1.1.tgz
npm http 200 https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.5.31.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-1.4.3.tgz

> opencv@3.0.0 install /home/root/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz
node-pre-gyp http 403 https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz
node-pre-gyp http 403 status code downloading tarball (falling back to source compile with node-gyp)
make: Entering directory '/home/root/node_modules/opencv/build'
  CXX(target) Release/obj.target/opencv/src/init.o
  CXX(target) Release/obj.target/opencv/src/Matrix.o
  CXX(target) Release/obj.target/opencv/src/OpenCV.o
  CXX(target) Release/obj.target/opencv/src/CascadeClassifierWrap.o
  CXX(target) Release/obj.target/opencv/src/Contours.o
  CXX(target) Release/obj.target/opencv/src/Point.o
  CXX(target) Release/obj.target/opencv/src/VideoCaptureWrap.o
  CXX(target) Release/obj.target/opencv/src/CamShift.o
  CXX(target) Release/obj.target/opencv/src/HighGUI.o
  CXX(target) Release/obj.target/opencv/src/FaceRecognizer.o
  CXX(target) Release/obj.target/opencv/src/BackgroundSubtractor.o
  CXX(target) Release/obj.target/opencv/src/Constants.o
  CXX(target) Release/obj.target/opencv/src/Calib3D.o
  CXX(target) Release/obj.target/opencv/src/ImgProc.o
  SOLINK_MODULE(target) Release/obj.target/opencv.node
/usr/lib/gcc/i586-poky-linux/4.8.2/../../../../i586-poky-linux/bin/ld: cannot find -lopencv_ts
collect2: error: ld returned 1 exit status
opencv.target.mk:148: recipe for target 'Release/obj.target/opencv.node' failed
make: *** [Release/obj.target/opencv.node] Error 1
make: Leaving directory '/home/root/node_modules/opencv/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 3.8.7-yocto-standard
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=opencv" "--configuration=Release" "--module_name=opencv" "--version=3.0.0" "--major=3" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=ia32" "--target_arch=ia32" "--module_main=./lib/opencv" "--host=https://node-opencv.s3.amazonaws.com/" "--module_path=/home/root/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-linux-ia32" "--module=/home/root/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-linux-ia32/opencv.node" "--remote_path=./opencv/v3.0.0/Release/" "--package_name=node-v11-linux-ia32.tar.gz" "--staged_tarball=build/stage/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz" "--hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/" "--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz"
gyp ERR! cwd /home/root/node_modules/opencv
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=ia32 --target_arch=ia32 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/home/root/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-linux-ia32 --module=/home/root/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-linux-ia32/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v11-linux-ia32.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/root/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:753:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:5)
node-pre-gyp ERR! System Linux 3.8.7-yocto-standard
node-pre-gyp ERR! command "node" "/home/root/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/root/node_modules/opencv
node-pre-gyp ERR! node -v v0.10.28
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=ia32 --target_arch=ia32 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/home/root/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-linux-ia32 --module=/home/root/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-linux-ia32/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v11-linux-ia32.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz' (1)
npm ERR! opencv@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@3.0.0 install script.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.7-yocto-standard
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "opencv"
npm ERR! cwd /home/root
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/root/npm-debug.log
npm ERR! not ok code 0

**Comment by peterbraden** [comment]
Doesn't look like you have opencv installed?

**Comment by AdamMiltonBarker** [comment]
This is over a year old, the issue was that it would not install.

**Comment by danschultzer** [comment]
`/usr/lib/gcc/i586-poky-linux/4.8.2/../../../../i586-poky-linux/bin/ld: cannot find -lopencv_ts` gives away that opencv is not installed, or the libraries are not built/linked. In the latter, it could also be that it's just `opencv_ts` missing which might [be resolved by](https://bugs.archlinux.org/task/37754) building with staticlibs.
