### ISSUE TITLE
Convert frame to JPEG

### ISSUE THREAD

**Issue by pfnegrini** [peterbraden/node-opencv#252]
I cannot find in the /src folder any reference to [imencode](http://docs.opencv.org/3.0-beta/modules/imgcodecs/doc/reading_and_writing_images.html#imencode)

Am I missing something? can this be implemented?
Basically i just need to convert a frame in memory to JPEG to stream it video using MJPEG streamer.

My workflow is:
1/ acquire video via openCV VideoCapture(0)
2/ process frame using OpenCV (example draw lines, text, etc)
3/ convert to JPEG => Missing instruction?
4/ stream via MJPEG using for example [node-mjpeg-server](https://github.com/gluxon/node-mjpeg-server/blob/master/examples/server.js)

Thanks!

**Comment by JesusIslam** [comment]
As far as I know, the image is already in JPEG if you do `image.toBuffer()`
