### ISSUE TITLE
Kernel size for erode/dilate

### ISSUE THREAD

**Issue by lomori** [peterbraden/node-opencv#254]
Hi,

Is there a way to define the kernel size for erode and dilate?

Cheers,
Luiz

**Comment by danschultzer** [comment]
[Yes](https://github.com/peterbraden/node-opencv/blob/13a1de4f9259b5e745021f3198a8339ac99edecd/src/Matrix.cc#L1411):

```
im.dilate(1, kernel);
im.erode(1, kernel);
```
