### ISSUE TITLE
OpenCV Installation problem

### ISSUE THREAD

**Issue by ibmStudio** [peterbraden/node-opencv#255]
Hi Sirs,
II will like to have a semplified procedure to understand what I need to do to install OPENCV 3.0.0 (x64 Windows 8.1) because when I run "npm install opencv" the procedure fails.
I installed :
a) Node version 0.12.2
b) npm version 2.7.4 (global installation)
b) OPENCV 3.0.0 and defined OPENCV_DIR (c:\Opencv_300\Build\x64 \vc12).
c) I create a working folder "C:\Server Node " where I installal webrtc module with success.
b) Installed (locally) node-pre-gyd with success.
e) I download also "pkg-config.exe" and create PKG_CONFIG_PATH that refers the folder where I store the opencv_x64.pc file with following contents:
# Package Information for pkg-config
opencv_prefix=C:/OpenCV_300/build/x64/vc12
exec_prefix=${opencv_prefix}/bin
libdir=${opencv_prefix}/lib
includedir=C:/OpenCV_300/build/include
Name: OpenCV
Description: Open Source Computer Vision Library
Version: 3.0.0
Cflags: ${includedir} ${includedir}/opencv
Libs: ${libdir}/opencv_world300 ${libdir}/opencv_ffmpeg300_64 

So, I not understand if I need to run "pkg-config.exe" and in which way.
Your help will be too appreciated because in internet I found a lot of omissis

**Comment by danschultzer** [comment]
Could you post the output? This might be a similar issue to #441. Since it's more than a year old, I'll close it for now, but reply if you still have issues.
