### ISSUE TITLE
update nan to work with io.js 2.x.x

### ISSUE THREAD

**Issue by markzrt** [peterbraden/node-opencv#256]
hi, the problem is..... you know : 

 ...return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);

please :D

**Comment by eljefedelrodeodeljefe** [comment]
@peterbraden is someone actively working on a port to `Nan@2.0.0`. Also maybe porting to OpenCV 3.0 #273 might be related. For NAN there currently is no [migration guide and known issues](https://github.com/nodejs/nan/issues/389). 
Both are intertwined, yet it's very worth the shot. I could send in a PR after this week, if no-one is working on it.

**Comment by peterbraden** [comment]
I'd love a PR :) AFAIK nobody is working on it yet.

**Comment by danschultzer** [comment]
Nan has been upgraded to v2.0.9 in #309. Latest release of `node-opencv` also works with OpenCV 3.0.
