### ISSUE TITLE
Problem installing version 3.0.1 (missing tarball)

### ISSUE THREAD

**Issue by mcilhargey** [peterbraden/node-opencv#257]
Windows 8, node 0.12.4, npm 2.10.1

Trying to install the package would always fail back to build, due to the following error: 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://node-opencv.s3.amazonaws.com/opencv/v3.0.1/Release/node-v14-win32-x64.tar.gz

I was able to install from a local copy of the package by rolling the version back to 3.0.0. I suspect there is a missing version from the aws account.

**Comment by iammoen** [comment]
Thinking that there might be something up with the AWS account as a whole. Can't get 3.0.1 or 3.0.0 either.

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>164B12D1A0DF7315</RequestId>
<HostId>
/IDih1eReBfJbRSpbTxOfPGPJQ3NHJhiDXn4Y372QCGJGzaquBvcZXN3Y03q7cf9
</HostId>
</Error>

**Comment by jyounus** [comment]
I have the exact same issue but on OS X.

```
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ee-face-detection" "--save"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@3.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jayy/Documents/intrepid_api/npm-debug.log
```


I've pasted the content of the debug log here: http://pastebin.com/SCqEyD9C

Any help would be appreciated.

**Comment by beautifullife** [comment]
I have the same problem on my Window 8.1 & Debian. Many thanks for any help!

**Comment by iammoen** [comment]
wondering if we can find anyone out there that still has a tarball of one of the versions...

**Comment by danschultzer** [comment]
I assume you can still build it successfully?

**Comment by danschultzer** [comment]
In light of this being more than a year old, I'll close the issue. Reply, and I'll reopen.

**Comment by onelifemedia** [comment]
I had the same issue today

**Comment by danschultzer** [comment]
@onelifemedia can you post output? What version of node-opencv do you use?
