### ISSUE TITLE
Need arm platform binary.

### ISSUE THREAD

**Issue by rippertnt** [peterbraden/node-opencv#263]
Hi. I tried to install node-opencv on my raspberry pi.
But I found some non-exist file of platform.

Binary package storage : https://node-opencv.s3.amazonaws.com

Cannot find https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-linux-arm.tar.gz
That made the malfunction to install this package on raspberry pi.

Do you have any plan to put the those file?

**Comment by dataTracer1975** [comment]
visit https://www.sitepoint.com/face-detection-nodejs-opencv/ for more info on how to install on RPi.
worked for me

**Comment by danschultzer** [comment]
No plans, you should just compile `node-opencv`.
