### ISSUE TITLE
ImageSimilarity 

### ISSUE THREAD

**Issue by Anslem** [peterbraden/node-opencv#264]
I try to use function ImageSimilarity, but dissimilarity allways equal NaN. The example dissimilarity.js also gives NaN.  Can I understand, what is a reason?

**Comment by sleungcy** [comment]
Hi, I am having the exact same issue too. Can anybody help?

**Comment by sleungcy** [comment]
@Anslem What was the size of the files you were comparing? I am testing out smaller images with width < 50 and can consistantly get this issue. 
Also, I worked pass this issue by scaling up the image to 100px, the image works again then.

**Comment by davduran** [comment]
I'm using this and works well: https://www.npmjs.com/package/phash

**Comment by AVVS** [comment]
https://github.com/AVVS/image-tag - this one is for tagging images / face detection

**Comment by jhedin** [comment]
The example gives NaN because it's not actually opening the pictures. Thus it passes in two empty matrices, and finds no matches.

I'm finding that Image similarity doesn't call it's callback when it *is* given images.
