### ISSUE TITLE
Problem with implementing from c++

### ISSUE THREAD

**Issue by kozer** [peterbraden/node-opencv#267]
I wrote a code in c++ that uses mat's data and step properties...
Is there a way to get the same properties from nodejs.
There is no such thing as .step or .data.I ve found that node gives a ptr function which uses the line as parameter, but how i can access these from the buffer it returns.

As an example, in c++ i do something like this
 double opacity = ((double)foreground.data[fY * foreground.step + fX * foreground.channels() + 3])/ 255.0;
     
Thanks a lot!

**Comment by danschultzer** [comment]
For data you could use `.getData`, but `step` is not exposed.
