### ISSUE TITLE
OpenCV v3.0.0 compatibility

### ISSUE THREAD

**Issue by artynet** [peterbraden/node-opencv#273]
Is the latest master ready to be used with the latest version of OpenCV ?

Regards, Arturo

**Comment by xinshouke** [comment]
It means the node-opencv doesn't support opencv3.0 yet?

**Comment by younes200** [comment]
any update on this ?

**Comment by peterbraden** [comment]
This is being worked on here: #259

**Comment by danschultzer** [comment]
It works with the latest release.

**Comment by adius** [comment]
Than you should update the readme!?
