### ISSUE TITLE
Incorrect rectangle drawing in examples/face-detection-rectangle.js

### ISSUE THREAD

**Issue by drejkim** [peterbraden/node-opencv#274]
In `examples/face-detection-rectangle.js`, should the following line:

```js
im.rectangle([face.x, face.y], [face.x + face.width, face.y + face.height], COLOR, 2);
```

be changed to:

```js
im.rectangle([face.x, face.y], [face.width, face.height], COLOR, 2);
```
The latter appears to draw the correct rectangle around Mona Lisa's face.

**Comment by Queuecumber** [comment]
Yup if you examine the code in Matrix.cc you can see that the second array should be width,height and not x2,y2.
