### ISSUE TITLE
Find-Object integration

### ISSUE THREAD

**Issue by lucmichalski** [peterbraden/node-opencv#291]
It would be interesting to have have the following repo integrated to node-opencv:
https://github.com/introlab/find-object/

Would be great to have SURF, FAST, BRIEF, AGAST, MSER and other feature detectors and descriptors, and be able to manage parameters like in Find-Object (https://github.com/introlab/find-object) with a JSON or INI file. And last thing, to build an inverted visual vocabulary to add multi objects detection.

Here a couple of tutorials about Find-Object:
https://github.com/introlab/find-object/wiki/TcpRequest
https://github.com/introlab/find-object/wiki/BeersWall
https://github.com/introlab/find-object/wiki/InvertedSearch

**Comment by danschultzer** [comment]
This is outside the scope of this library.
