### ISSUE TITLE
Windows 10 + npm install opencv Error

### ISSUE THREAD

**Issue by onsterion** [peterbraden/node-opencv#311]
Hi all,

I'm new with openCV and i found node-opencv but i can't install the pack.

I'm using opencv 2.4.10 - Python 2.7 32bits - numpy 1.9.2. (the examples in python works fine)

Error:

> opencv@3.2.0 install C:\Users\onste\node_modules\opencv
> node-pre-gyp install --fallback-to-build

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

C:\Users\onste\node_modules\opencv>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.2.0 --major=3 --minor=2 --runtime=node --node_abi=node-v46 --platform=win32 --target_platform=win32 --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=C:\Users\onste\node_modules\opencv\build\opencv\v3.2.0\Release\node-v46-win32-x64 --module=C:\Users\onste\node_modules\opencv\build\opencv\v3.2.0\Release\node-v46-win32-x64\opencv.node --remote_path=./opencv/v3.2.0/Release/ --package_name=node-v46-win32-x64.tar.gz --staged_tarball=build\stage\opencv\v3.2.0\Release\node-v46-win32-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/node-v46-win32-x64.tar.gz )  else (node  rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.2.0 --major=3 --minor=2 --runtime=node --node_abi=node-v46 --platform=win32 --target_platform=win32 --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=C:\Users\onste\node_modules\opencv\build\opencv\v3.2.0\Release\node-v46-win32-x64 --module=C:\Users\onste\node_modules\opencv\build\opencv\v3.2.0\Release\node-v46-win32-x64\opencv.node --remote_path=./opencv/v3.2.0/Release/ --package_name=node-v46-win32-x64.tar.gz --staged_tarball=build\stage\opencv\v3.2.0\Release\node-v46-win32-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/node-v46-win32-x64.tar.gz )
"pkg-config" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
gyp: Call to 'pkg-config --cflags "opencv >= 2.4.9"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--name=opencv" "--configuration=Release" "--module_name=opencv" "--version=3.2.0" "--major=3" "--minor=2" "--runtime=node" "--node_abi=node-v46" "--platform=win32" "--target_platform=win32" "--arch=x64" "--target_arch=x64" "--module_main=./lib/opencv" "--host=https://node-opencv.s3.amazonaws.com/" "--module_path=C:\\Users\\onste\\node_modules\\opencv\\build\\opencv\\v3.2.0\\Release\\node-v46-win32-x64" "--module=C:\\Users\\onste\\node_modules\\opencv\\build\\opencv\\v3.2.0\\Release\\node-v46-win32-x64\\opencv.node" "--remote_path=./opencv/v3.2.0/Release/" "--package_name=node-v46-win32-x64.tar.gz" "--staged_tarball=build\\stage\\opencv\\v3.2.0\\Release\\node-v46-win32-x64.tar.gz" "--hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/" "--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/node-v46-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\onste\node_modules\opencv
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.2.0 --major=3 --minor=2 --runtime=node --node_abi=node-v46 --platform=win32 --target_platform=win32 --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=C:\Users\onste\node_modules\opencv\build\opencv\v3.2.0\Release\node-v46-win32-x64 --module=C:\Users\onste\node_modules\opencv\build\opencv\v3.2.0\Release\node-v46-win32-x64\opencv.node --remote_path=./opencv/v3.2.0/Release/ --package_name=node-v46-win32-x64.tar.gz --staged_tarball=build\stage\opencv\v3.2.0\Release\node-v46-win32-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/node-v46-win32-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\onste\node_modules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:76:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\onste\\node_modules\\opencv\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\onste\node_modules\opencv
node-pre-gyp ERR! node -v v4.1.1
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.2.0 --major=3 --minor=2 --runtime=node --node_abi=node-v46 --platform=win32 --target_platform=win32 --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=C:\Users\onste\node_modules\opencv\build\opencv\v3.2.0\Release\node-v46-win32-x64 --module=C:\Users\onste\node_modules\opencv\build\opencv\v3.2.0\Release\node-v46-win32-x64\opencv.node --remote_path=./opencv/v3.2.0/Release/ --package_name=node-v46-win32-x64.tar.gz --staged_tarball=build\stage\opencv\v3.2.0\Release\node-v46-win32-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/node-v46-win32-x64.tar.gz' (1)
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "opencv"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@3.2.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\onste\npm-debug.log

Greetings.

**Comment by albertgarcias** [comment]
I have similar error in W7 node.js v4.1.1 x64 and openCV 2.4.11

**Comment by Royalxm** [comment]
i solution plz

**Comment by danschultzer** [comment]
You need to install pkg-config:

> "pkg-config" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Here's some instructions: http://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows
