### ISSUE TITLE
npm installation fail on Linux

### ISSUE THREAD

**Issue by Hosar** [peterbraden/node-opencv#312]
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-65-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=opencv"

---

npm ERR! Linux 3.13.0-65-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "opencv"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@3.2.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

**Comment by jas0n1ee** [comment]
Got the same error(configure.js:355:16) here on Mac OSX. But I think [this](https://travis-ci.org/peterbraden/node-opencv) may help you since you are running linux.

**Comment by jas0n1ee** [comment]
@Hosar check [this](https://travis-ci.org/peterbraden/node-opencv), the last step `node-pre-gyp info` actually gives an error.

**Comment by jas0n1ee** [comment]
@Hosar see issue #266 , if you every install opencv from source code or something else, try uninstall it and then try `npm install opencv` or `npm install --build-from-source` at this repo's directory.  I have successfully install node-opencv on a ubuntu and a mac.
