### ISSUE TITLE
Does this installation works ?

### ISSUE THREAD

**Issue by Nishanksingla** [peterbraden/node-opencv#333]
unable to install node-opencv.
Anyone able to install it ?
I am getting the same error as everyone. 
"node-pre-gyp install --fallback-to-build"

does not name a type
   cv::CascadeClassifier cc;
       ^
In file included from ../src/init.cc:6:0:
../src/VideoCaptureWrap.h:5:11: error: ‘VideoCapture’ in namespace ‘cv’ does not name a type
       cv::VideoCapture cap;
           ^
In file included from ../src/init.cc:15:0:
../src/Stereo.h:8:9: error: ‘StereoBM’ in namespace ‘cv’ does not name a type
     cv::StereoBM stereo;

Please help me

**Comment by t0ken** [comment]
I have the same problem. 
```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "opencv"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.2.0 install: `node-pre-gyp install --fallback-to-build`
```
anyone who succeeded to install node-opencv pls tell us which version of node node-gyp node-pre-gyp and npm you use

**Comment by Nishanksingla** [comment]
i am also having the same versions of node and npm and getting the same thing in the end. 
Please help.. Anyone
I am having the following configuration
 Ubuntu 15.04
OpenCV 3.0.0
Node 4.2.2
Npm 2.14.7

**Comment by koalazak** [comment]
Hi guys,
the build is passing for Linux. I suggest to you that see the [.travis.yml](https://github.com/peterbraden/node-opencv/blob/master/.travis.yml)  file (sections before_install and install) to check if you have all the things on place.
(i dont know why the build checking for osx is off)

best regards,

**Comment by Nishanksingla** [comment]
Yes it is but only for opencv 2.4 version not for opencv 3.0 or greater.

**Comment by tim-kos** [comment]
I am also suffering from the same problem. Same opencv, node, ubuntu, npm versions.

In the travis.yml file it says;

node_js:
  - '0.12'

So does this means node 4.x or even 5.x aren't supported yet? If so, will they be supported anytime soon?

**Comment by Nishanksingla** [comment]
I was able to install it by using 
Opencv 2.4 
Latest npm (5.x.x) 
Node 4.2.2
Ubuntu 14.04

**Comment by abedzantout** [comment]
@Nishanksingla Could you please post what you did?

**Comment by SimplyY** [comment]
@abedzantout 
At first, i install by using opencv3 ,don't work like @Nishanksingla 

```
does not name a type
cv::CascadeClassifier cc;
```

then, I install  Opencv 2.4.9 and then work~

**Comment by abedzantout** [comment]
@SimplyY 
I made it work last night.

to anyone that may face future issues on mac OS,

1-install npm
2- install opencv using brew
3- go to your project and ```npm install node-pre-gyp```
4- ``` npm install opencv`` (if this doesn't work, simply download from the source, cd to the folder and ```npm install```, then ```npm install``` from the project.
5- you're done.

happy coding!

**Comment by erikusaj** [comment]
Same issue. Tried several Docker images "node" and "opencv" -none worked so far. 
Adding to this issue after 2 nights of try & fail.
note: Fails also with included Dockerfile.

``
npm ERR! Linux 4.4.8-boot2docker
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "opencv" "-g"
npm ERR! node v4.2.6
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE

npm ERR! opencv@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@5.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

**Comment by danschultzer** [comment]
@erikusaj can you post the full `/npm-debug.log` transcript?

**Comment by danschultzer** [comment]
I'll close this for now. Please reply if you still experience issues, and I'll reopen the issue.
