### ISSUE TITLE
Error: Image has no size

### ISSUE THREAD

**Issue by briviere** [peterbraden/node-opencv#337]
Hello 

I'm running the convert-image.js example and get the following error:

Error: Image has no size

I'm running on the following:

Linux 2 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

opencv 2.4.11

All of the image examples are throwing this error.

thanks

Brian

**Comment by jamesmoey** [comment]
Make sure you are running the example inside the example directory.

**Comment by danschultzer** [comment]
I assume this has been resolved. Will reopen if you still have issues.
