### ISSUE TITLE
From grayscale to color image error

### ISSUE THREAD

**Issue by Taberu** [peterbraden/node-opencv#345]
Hello, I'm trying to transform a grayscale image to a RGB jpg, using im.cvtColor('CV_GRAY2RGB') but I get this error:

OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/color.cpp, line 3648
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/color.cpp:3648: error: (-215) scn == 3 || scn == 4 in function cvtColor

how can I do it?

**Comment by jspdown** [comment]
`CV_GRAY2RGB` doesn't exists on `node-opencv`. Available constants are described [here](https://github.com/peterbraden/node-opencv/blob/d7b7161871499871e539945a4d33cb1b5fe0956e/src/Matrix.cc#L2002-L2043)

**Comment by danschultzer** [comment]
`CV_GRAY2BGR` do exist in latest release of opencv (5.0.0), so this should work now.
