### ISSUE TITLE
detectObject causing weird behavior

### ISSUE THREAD

**Issue by Fruchtsbold** [peterbraden/node-opencv#348]
Hello!

after struggling with npm 2 days, i finally managed to install the node-opencv module. 

Now i am testing the examples delivered and i expirienced very weird behavoir of the im.detectObject()-method. I tried out examples like the camera-example which worked fine. I also managed to modify images from a file or from the camera but i could not get the face-detection-example to work. It seems like the method crashes everything when it gets results in the callback-method.

If i use something like that: 

```
cv.readImage("./files/mona.jpg", function(err, im){
	im.detectObject('../data/haarcascade_frontalface_default.xml', {}, function(err, faces){
		if (!faces.length){console.log("No Faces")}

		for (var i=0;i<faces.length; i++){
		  var x = faces[i]
		  im.ellipse(x.x + x.width/2, x.y + x.height/2, x.width/2, x.height/2);
		}
     	  im.save('./out.jpg');

 		console.log('Done');
	  });
})
```

i get no output at all. no errors, no console-output and most important no output image. 

but if i replace the mona lisa image with the coin1 image, i get the console-outpit "No Faces Done".

I would be very thankful if somebody could help me with my problem.

Thanks!

**Comment by danschultzer** [comment]
Running the following code works:

```javascript
cv.readImage("./node_modules/opencv/examples/files/mona.png", function(err, im){
    im.detectObject('./node_modules/opencv/data/haarcascade_frontalface_default.xml', {}, function(err, faces){
        if (!faces.length) {
          console.log("No Faces");
        }

        for (var i=0;i<faces.length; i++){
          var x = faces[i];
          im.ellipse(x.x + x.width/2, x.y + x.height/2, x.width/2, x.height/2);
        }
          im.save('./out.jpg');

        console.log('Done');
      });
});
```
