### ISSUE TITLE
npm install failed in Debian 7.9

### ISSUE THREAD

**Issue by cpena** [peterbraden/node-opencv#352]
Hi!,
I'm trying to install node-opencv in Debian 7.9 but always said **"Package opencv was not found in the pkg-config search path."** and PKG_CONFIG_PATH is configured!, 
Someone could help me?
```
...
OpenCV 2.4.9 ready to be used
$> echo $PKG_CONFIG_PATH
/usr/local/lib/pkgconfig/

$> npm install opencv

> opencv@4.0.0 install /home/christian/app/node_modules/opencv
> node-pre-gyp install --fallback-to-build

Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
...
```
Regards from Chile,
Christian

**Comment by peterbraden** [comment]
What do you get from `pkg-config --libs opencv` ? Looks like you need to add opencv to your package config path.
