### ISSUE TITLE
npm build opencv with wrong path

### ISSUE THREAD

**Issue by jimmyzzzzzzz** [peterbraden/node-opencv#353]
I got an error when I run example programs. 
Library not loaded: /usr/local/opt/opencv/lib/libopencv_calib3d.2.4.dylib
libopencv_calib3d.2.4.dylib is actually in /usr/local/Cellar/opencv/2.4.12/lib/
also /usr/local/opt/opencv/lib/ is mentioned in /node_modules/opencv/build/Release/opencv.node
I installed opencv with brew on my mac and I installed node opencv with npm install opencv
also /usr/local/opt/ is not in my environment variables.
Please help me

**Comment by arimai** [comment]
brew should have installed all the libraries and created links for you in place. 
Try removing opencv and reinstalling it through brew and make sure you do `brew link opencv`. 
If that doesn't work after installation, try `brew link --overwrite --dry-run opencv`

**Comment by danschultzer** [comment]
As @arimai writes, `brew link` is the way to fix it.
