### ISSUE TITLE
Support more Unix platforms in the node-gyp build process

### ISSUE THREAD

**Issue by rse** [peterbraden/node-opencv#354]
Currently, the binding.gyp uses pkg-config just under Linux. But node-gyp knows also about "freebsd", "openbsd", "solaris" and "aix" as identifiers for variable OS. Especially, "freebsd" was missing for my case. Please apply the following patch so your module builds on non-Linux Unix platforms, too.

```
diff --git a/binding.gyp b/binding.gyp
index 8cde338..7eebd03 100755
--- a/binding.gyp
+++ b/binding.gyp
@@ -37,7 +37,7 @@
       "cflags_cc!": [ "-fno-rtti",  "-fno-exceptions"],
 
       "conditions": [
-        [ "OS==\"linux\"", {
+        [ "OS==\"linux\" or OS==\"freebsd\" or OS==\"openbsd\" or OS==\"solaris\" or OS==\"aix\"", {
             "cflags": [
               "<!@(pkg-config --cflags \"opencv >= 2.3.1\" )",
               "-Wall"
```

**Comment by peterbraden** [comment]
Please can you leave a PR?

**Comment by rse** [comment]
For just this single-line(!) change? Instead, could you please just copy & paste this simple change? Thanks.
