### ISSUE TITLE
including opencv module in an nwjs app results in an error

### ISSUE THREAD

**Issue by plexigras** [peterbraden/node-opencv#360]
"Uncaught Error: Cannot find module 'pathToApp/node_modules/opencv/build/opencv/v4.0.0/Release/node-webkit-v0.12.3-linux-x64/opencv.node'", source: module.js (329)

**Comment by peterbraden** [comment]
It doesn't look like nwjs supports native modules, you need to build them manually, see:

https://github.com/nwjs/nw.js/wiki/build-native-modules-with-nw-gyp
