### ISSUE TITLE
ERROR npm install opencv

### ISSUE THREAD

**Issue by novamahend** [peterbraden/node-opencv#364]
Hi there, I am using windows, and I have error message when install it in the CMD ("fallback to build"). What should I do to fix it?
Once more I still dont know about this direction : 
"If you haven't already, create a system variable called OPENCV_DIR and set it to C:\OpenCV\build\x64\vc12
Make sure the "x64" part matches the version of NodeJS you are using.
Also add the following to your system PATH ;%OPENCV_DIR%\bin
Install Visual Studio 2013. Make sure to get the C++ components. You can use a different edition, just make sure OpenCV supports it, and you set the "vcxx" part of the variables above to match."\

Thank you very much :-)

**Comment by peterbraden** [comment]
You need to point to the path where you've installed opencv.
