### ISSUE TITLE
type_info Build Error

### ISSUE THREAD

**Issue by AwooOOoo** [peterbraden/node-opencv#370]
Hi,
    I seem to be unable to build the latest the node-opencv as I'm getting some ambiguous symbol errors regarding the use of type_info when running 'npm install'. This is my first time building this so the issue could be on my side.

**node-opencv**: latest checkout
OpenCV version: 2.4.10 
Node version: 4.3.0 
Visual Studio: 2013**

  I've tried pointing (with OPENCV_DIR env var) at both the x86 and x64 opencv builds with their respective node install and get the same error. Builiding the VS solution directly also provides the same type_info errors as expected.

A pipe of the console output is attached 
[console.txt](https://github.com/peterbraden/node-opencv/files/127649/console.txt)

A pipe of the npm errors to the console is attached
[console2.txt](https://github.com/peterbraden/node-opencv/files/127653/console2.txt)

The npm debug file is attached.
[npm-debug.txt](https://github.com/peterbraden/node-opencv/files/127647/npm-debug.txt)

Any help in getting this up and running would be appreciated.

Sincerely, Paul.

**Comment by AwooOOoo** [comment]
Ok fixed,
    There seems to be some namespace pollution with std in a few files. Commented out "using namespace std;" in both VideoCaptureWrap.cc and Contours.h. The VideoCaptureWrap.cc wasn't needed anyway, but the Contours.h one required me to correct all the references by hand by prefixing with "std::". It compiles fine now.

Paul.

**Comment by AwooOOoo** [comment]
changes pushed for review.

**Comment by peterbraden** [comment]
Did you make a PR? I don't see it.

**Comment by AwooOOoo** [comment]
Sorry, it should be there now...
