### ISSUE TITLE
Failure to install on Raspberry Pi 2 running Raspbian

### ISSUE THREAD

**Issue by justin97530** [peterbraden/node-opencv#373]
Hey guys, I tried install node-opencv today on my Pi, however I ran across this issue: http://pastebin.com/J6F5mnfi

My node version is 5.6.0, npm version is 3.6.0, and according to dpkg, opencv 2.4.9.1 is installed.
(http://pastebin.com/jBBLULZq)
Any help would be appreciated.

**Comment by keeganbrown** [comment]
Why are you installing as root? Have you tried just `npm install opencv`

**Comment by justin97530** [comment]
I have, that didn't work either.

**Comment by dataTracer1975** [comment]
I have installed it on a RPi v3 with no problems.
I have followed the instructions found here https://www.sitepoint.com/face-detection-nodejs-opencv/
```
sudo apt-get install build-essential
sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
sudo apt-get install libopencv-dev
```
You’ll also need Imagemagick, which is a dependency of the image-processing library we’re going to be using.
```
apt-get install imagemagick
```

**Comment by danschultzer** [comment]
You don't get a different error when you install it as just `npm install opencv`?

I believe @dataTracer1975 comment explains how to install all necessary libraries to get it working on RPi. I'll close this for now, but reopen if you still have any issues.
