### ISSUE TITLE
error when use toBuffer

### ISSUE THREAD

**Issue by armst0910** [peterbraden/node-opencv#374]
I have using node-opencv 5.0.0 with opencv 2.4.11 
when I use to convert image to buffer it got an error so my application was crashed
any idea to fix it ? or what should I do ?

**Comment by jamesmoey** [comment]
What error did you get?

**Comment by gfarioli** [comment]
Hi, 
I have the same problem, using node-opencv 5.0.0 with opencv 2.4.9, on Windows 10 sp1.
The error is:
`OpenCV Error: Unknown error code -10 (Raw image encoder error: Empty JPEG image (DNL not supported)) in cv::BaseImageEncoder::throwOnEror on \opencv\modules\highgui\src\grfmt_base.cpp, line 131.`

**Comment by danschultzer** [comment]
I can't replicate this error:

```javascript
var cv = require("opencv");
cv.readImage('image.jpg', function(err, img){
  if(err) throw err;
  var buffer = img.toBuffer();
  console.log("Buffered");
});
```

I'll close this for now, but if you continue to have this issue, please post example code.

**Comment by r3verser** [comment]
Have the same issue. Even your short example not working, just crashes without any error in console!
Windows 7 x64
node 7.1.0
"opencv": "^6.0.0"

**Comment by r3verser** [comment]
Fixed! The problem was at MS Build tools version, i have v14 so downloaded opencv for ms build tools 14
