### ISSUE TITLE
Can't install on os x

### ISSUE THREAD

**Issue by JohnAllen** [peterbraden/node-opencv#380]
Can't install this on OS X.  Tried quite a few different combos of Node and tried installing node-opencv from source like was suggested in another install issue.

I have OpenCV 2.4.12_2 installed using brew.

Would be great if someone using this on a Mac could help out.  Other install issues were windows or Ubuntu...

`/usr/local/Cellar/opencv/2.4.12_2/include/opencv2/ml/ml.hpp:877:26: note: hidden overloaded virtual function 'CvDTree::train' declared here: different number of parameters (8 vs 3)
    CV_WRAP virtual bool train( const cv::Mat& trainData, int tflag,
                         ^
2 warnings generated.
  CXX(target) Release/obj.target/opencv/src/LDAWrap.o
  SOLINK_MODULE(target) Release/opencv.node
ld: library not found for -llibtbb.dylib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/opencv.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/johnallen/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/johnallen/.nvm/versions/node/v5.3.0/bin/node" "/Users/johnallen/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/johnallen/opencv-haar-classifier-training/node_modules/node-opencv/build/opencv/v5.0.0/Release/node-v47-darwin-x64/opencv.node" "--module_name=opencv" "--module_path=/Users/johnallen/opencv-haar-classifier-training/node_modules/node-opencv/build/opencv/v5.0.0/Release/node-v47-darwin-x64"
gyp ERR! cwd /Users/johnallen/opencv-haar-classifier-training/node_modules/node-opencv
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
`

More error output here:

<img width="1268" alt="screen shot 2016-02-26 at 4 49 35 pm" src="https://cloud.githubusercontent.com/assets/2800641/13369389/012b7d16-dca9-11e5-9fa0-9a45ef8e4fde.png">

**Comment by bouriate** [comment]
Try set PKG_CONFIG_PATH env before install:

   $ export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

**Comment by RubenCordeiro** [comment]
I experienced this error when I ran ```npm install opencv```:
```
/Users/rubencordeiro/node_modules/opencv/utils/find-opencv.js:21
                throw new Error("ERROR: failed to run: pkg-config", opencv, flag);
                ^

Error: ERROR: failed to run: pkg-config
    at /Users/rubencordeiro/node_modules/opencv/utils/find-opencv.js:21:23
    at ChildProcess.exithandler (child_process.js:210:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

I installed opencv (2.4.12_2) through homebrew.

I solved the issue by reinstalling pkg-config by running: ``` brew reinstall pkg-config ```

My error output is different from the owner, but I hope this helps someone who experienced the same issue as mine.

**Comment by JohnAllen** [comment]
A workaround for my problem, which seems different than yours, @RubenCordeiro, is that I had opencv installed with -tbb, which allows for multithreaded cascade training.

**Comment by ubuntugx** [comment]
@RubenCordeiro it is work for me. Thanks a lot. :)

**Comment by sineveel** [comment]
@RubenCordeiro Thank You very much)))

**Comment by sineveel** [comment]
@RubenCordeiro Thank You very much)))

**Comment by jfroffice** [comment]
I am still having this issue
```
> opencv@6.0.0 install /Users/jfischer/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v48-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@6.10.3 (node-v48 ABI) (falling back to source compile with node-gyp)
/Users/jfischer/node_modules/opencv/utils/find-opencv.js:21
                throw new Error("ERROR: failed to run: pkg-config", opencv, flag);
                ^

Error: ERROR: failed to run: pkg-config
    at /Users/jfischer/node_modules/opencv/utils/find-opencv.js:21:23
    at ChildProcess.exithandler (child_process.js:211:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
gyp: Call to 'node utils/find-opencv.js --cflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
````
even with @RubenCordeiro tricks
