### ISSUE TITLE
error install : any.h(48): error C2039: 'type_info' 

### ISSUE THREAD

**Issue by Royalxm** [peterbraden/node-opencv#382]
Log  :
http://pastebin.com/NzsHSDwY

i run npm install opencv and i have this error :
opencv2\flann\any.h(48): error C2039: 'type_info' : n'est pas membre de 'std'  [C:\Users\Royal\D
esktop\test3\node_modules\opencv\build\test_nativemat.vcxproj]

**Comment by nastakhov** [comment]
+1

**Comment by affanshahid** [comment]
Same error. Windows 10, OpenCV 2.4.11, Node 5.10.0, npm 3.8.3

**Comment by Chanyou** [comment]
@affanshahid It works! Thanks so much!

**Comment by danschultzer** [comment]
This might have been fixed with #371. I'll close this for now.
