### ISSUE TITLE
how do i get color histogram ?

### ISSUE THREAD

**Issue by samurex** [peterbraden/node-opencv#385]
Hi, i need to find out a dominant color of given image, can I do that using node-opencv ?, thanks

**Comment by danschultzer** [comment]
Histogram works on single channel: http://docs.opencv.org/2.4/doc/tutorials/imgproc/histograms/histogram_calculation/histogram_calculation.html

**Comment by Nateowami** [comment]
@danschultzer Are there even bindings for `calcHist` though? I can't find it in the readme, on the wiki, in the examples, in the source code for the bindings, or mentioned in another issue.

**Comment by Schultzer** [comment]
@Nateowami you can use the fork of [farfromrefug] (https://github.com/farfromrefug/node-opencv) for
`calchist()` support

**Comment by danschultzer** [comment]
I'll see if I can set up a PR to add `calcHist`.

**Comment by Nateowami** [comment]
@danschultzer Thanks, that would be great.

**Comment by danschultzer** [comment]
Attempted to implement `calcHist`, but gave up since my C++ experience is minuscule. I think #290 could remove this need entirely.
