### ISSUE TITLE
How do you include OpenCV into a javascript project?

### ISSUE THREAD

**Issue by ShaunodCIT** [peterbraden/node-opencv#391]
I'm sorry if this seems like a really dumb question, but I'm honestly stuck here...

I posted this question on StackOverflow recently as well which can be found here:
http://stackoverflow.com/questions/36132670/how-do-you-include-opencv-into-a-javascript-project

This post is pretty much going to be a copy/paste of that question.

I recently installed OpenCV through npm using the following guide: https://www.npmjs.com/package/opencv

My question is pretty simple. How do I actually use the OpenCV library in my project?

On that site, there is a face detection example that looks like this:

cv.readImage("./examples/files/mona.png", function(err, im){
  im.detectObject(cv.FACE_CASCADE, {}, function(err, faces){
    for (var i=0;i<faces.length; i++){
      var x = faces[i]
      im.ellipse(x.x + x.width/2, x.y + x.height/2, x.width/2, x.height/2);
    }
    im.save('./out.jpg');
  });
})

The cv. variable is where I'm stuck at. Typically whenever I install a new package using npm, I would add it to my app.js file like so:

angular
  .module('App', [
    'ngAnimate',
    'ngCookies',
    'ngResource',
    'ngRoute',
    'ngSanitize',
    'ngTouch',
    'ui.sortable',
    'firebase',
    'angular-toArrayFilter'
  ])

Similarly in any of my controllers, I would add the name of the module as a parameter to the controller:

angular.module('App')
  .controller('LoginCtrl', function ($scope, UserAuth, $window, $firebaseArray, fireBaseRef)

I can't seem to find the dependency name for OpenCV to even allow me to use it in the first place. None of the guides that I've looked at to date ever mention how to include it into your project.

Thanks for your time!

**Comment by peterbraden** [comment]
The module name is 'opencv' as in `require('opencv')`
