### ISSUE TITLE
readImage(file) and readImage(buffer) load differently, should be the same

### ISSUE THREAD

**Issue by dxprog** [peterbraden/node-opencv#392]
https://github.com/peterbraden/node-opencv/blob/master/src/OpenCV.cc#L40

Calling `readImage` passing a file path calls `cv::imread` with no arguments, defaulting to `CV_LOAD_IMAGE_COLOR` and returns a 3-channel image. Reading from a buffer calls `cv::imdecode` and passes along the `CV_LOAD_IMAGE_UNCHANGED` which will, obviously, return all channels in the image. This became confusing when trying to call `convertGrayscale` on a PNG buffer only to have it throw an error claiming that the image was "no" 3 channel when loading the same image from disk worked just fine.

I'm cool with writing the patch myself, but this would be a breaking change to current behaviour and the question arises: which version changes? My personal thought is that both methods should use the `CV_LOAD_IMAGE_UNCHANGED`.

**Comment by peterbraden** [comment]
Using CV_LOAD_IMAGE_UNCHANGED sounds good, I can do a major version bump for a breaking change. Could you add a test in the patch.

Thanks!
