### ISSUE TITLE
How to recognize charactors(text) using node-opencv?

### ISSUE THREAD

**Issue by sureshkoduri** [peterbraden/node-opencv#399]
Hi, Im new to opencv. I want to recognize charactors in an image. How ? Please help me.

**Comment by dominikdolancic** [comment]
Function for recognizing chars not exist on this package, you can use node-tesseract for that

**Comment by TheRyanHickman** [comment]
@dominikdolancic i would strongly consider taking a look at tesseract.projectnaptha.com
