### ISSUE TITLE
binary thresholding 

### ISSUE THREAD

**Issue by ofirattia** [peterbraden/node-opencv#402]
any example for converting image to black and white?

**Comment by bradrisse** [comment]
Look in the examples folder for /examples/convert-image.js.

You can use im.convertGrayscale();

**Comment by kikaendeavor** [comment]
use cvtColor and inRange.

first:
convert image to gray level
`im.cvtColor('CV_BGR2GRAY');`

second: 
get Binary Image
`// (B)lue, (G)reen, (R)ed
var lower_threshold = [0, 0, 0];
var upper_threshold = [80, 96, 115];
im.inRange(lower_threshold, upper_threshold);`

now you get it.
