### ISSUE TITLE
Problem while installing this package on Heroku

### ISSUE THREAD

**Issue by dominikdolancic** [peterbraden/node-opencv#404]
What I'm doing wrong? I've set environment path for pkgconfig and lib also on opencv.pc.

`> fsevents@1.0.12 install /tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/nodemon/node_modules/chokidar/node_modules/fsevents
remote:        > node-pre-gyp install --fallback-to-build
remote:        
remote:        make: Entering directory /tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/nodemon/node_modules/chokidar/node_modules/fsevents/build'
remote:        SOLINK_MODULE(target) Release/obj.target/.node
remote:        COPY Release/.node
remote:        make: Leaving directory /tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/nodemon/node_modules/chokidar/node_modules/fsevents/build
remote:        
remote:        > opencv@5.0.0 install /tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/opencv
remote:        > node-pre-gyp install --fallback-to-build
remote:        
remote:        node-pre-gyp ERR! Tried to download: https://node-opencv.s3.amazonaws.com/opencv/v5.0.0/Release/node-v11-linux-x64.tar.gz
remote:        node-pre-gyp ERR! Pre-built binaries not found for opencv@5.0.0 and node@0.10.45 (node-v11 ABI) (falling back to source compile with node-gyp)
remote:        
remote:        /tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/opencv/utils/find-opencv.js:21
remote:        throw new Error("ERROR: failed to run: pkg-config", opencv, fl
remote:        ^
remote:        Error: ERROR: failed to run: pkg-config
remote:        at /tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/opencv/utils/find-opencv.js:21:23
remote:        at ChildProcess.exithandler (child_process.js:662:7)
remote:        at ChildProcess.emit (events.js:98:17)
remote:        at maybeClose (child_process.js:766:16)
remote:        at Socket.<anonymous> (child_process.js:979:11)
remote:        at Socket.emit (events.js:95:17)
remote:        at Pipe.close (net.js:466:12)
remote:        gyp: Call to 'node utils/find-opencv.js --cflags' returned exit status 8 while in binding.gyp. while trying to load binding.gyp
remote:        gyp ERR! configure error
remote:        gyp ERR! stack Error: `gyp` failed with exit code: 1
remote:        gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/node-gyp/lib/configure.js:305:16)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
remote:        gyp ERR! System Linux 3.13.0-79-generic
remote:        gyp ERR! command "/tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/.heroku/node/bin/node" "/tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/opencv/build/opencv/v5.0.0/Release/node-v11-linux-x64/opencv.node" "--module_name=opencv" "--module_path=/tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/opencv/build/opencv/v5.0.0/Release/node-v11-linux-x64"
remote:        gyp ERR! cwd /tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/opencv
remote:        gyp ERR! node -v v0.10.45
remote:        gyp ERR! node-gyp -v v3.3.1
remote:        gyp ERR! not ok
remote:        node-pre-gyp ERR! build error
remote:        node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/.heroku/node/bin/node /tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/opencv/build/opencv/v5.0.0/Release/node-v11-linux-x64/opencv.node --module_name=opencv --module_path=/tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/opencv/build/opencv/v5.0.0/Release/node-v11-linux-x64' (1)
remote:        node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
remote:        node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
remote:        node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
remote:        node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
remote:        node-pre-gyp ERR! System Linux 3.13.0-79-generic
remote:        node-pre-gyp ERR! command "node" "/tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
remote:        node-pre-gyp ERR! cwd /tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/opencv
remote:        node-pre-gyp ERR! node -v v0.10.45
remote:        node-pre-gyp ERR! node-pre-gyp -v v0.6.28
remote:        node-pre-gyp ERR! not ok
remote:        Failed to execute '/tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/.heroku/node/bin/node /tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/opencv/build/opencv/v5.0.0/Release/node-v11-linux-x64/opencv.node --module_name=opencv --module_path=/tmp/build_fe6fd03b8f565fb1b07dacccd99216cf/node_modules/opencv/build/opencv/v5.0.0/Release/node-v11-linux-x64' (1)
`

**Comment by dchun** [comment]
You need to add multiple buildpacks when building source like so:
```
heroku create myapp --buildpack heroku/nodejs
heroku buildpacks:add --index 1 https://github.com/automata/heroku-buildpack-opencv.git
```
or if your app has already been created:
```
heroku buildpacks:add heroku/nodejs
heroku buildpacks:add --index 1 https://github.com/automata/heroku-buildpack-opencv.git
```
[See the docs](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app#adding-a-buildpack)

**Comment by danschultzer** [comment]
Seems like @dchun's answer was sufficient. I'll close this issue.

**Comment by monarchpedo** [comment]
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=false
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  >=4.3 <7.0
remote:        engines.npm (package.json):   >=1.0.0
remote:
remote:        Resolving node version >=4.3 <7.0...
remote:        Downloading and installing node 6.11.3...
remote:        Bootstrapping npm >=1.0.0 (replacing 3.10.10)...
remote:        npm 5.4.2 installed
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (disabled)
remote:
remote: -----> Building dependencies
remote:        Prebuild detected (node_modules already exists)
remote:        Rebuilding any native modules
remote:
remote:        > uws@0.14.5 install /tmp/build_691c03bb9445cb4d916db850cd2f3fbd/node_modules/uws
remote:        > node-gyp rebuild > build_log.txt 2>&1 || exit 0
remote:
remote:
remote:        > v8-debug@1.0.1 preinstall /tmp/build_691c03bb9445cb4d916db850cd2f3fbd/node_modules/v8-debug
remote:        > node -e 'process.exit(0)'
remote:
remote:
remote:        > v8-debug@1.0.1 install /tmp/build_691c03bb9445cb4d916db850cd2f3fbd/node_modules/v8-debug
remote:        > node-pre-gyp install --fallback-to-build
remote:
remote:        sh: 1: node-pre-gyp: Permission denied
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 126
remote:        npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
remote:        npm ERR! Exit status 126
remote:        npm ERR!
remote:        npm ERR! Failed at the v8-debug@1.0.1 install script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /app/.npm/_logs/2017-09-23T09_19_33_695Z-debug.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - node_modules checked into source control
remote:        https://blog.heroku.com/node-habits-2016#9-only-git-the-important-bits
remote:
remote:        - Dangerous semver range (>) in engines.node
remote:        https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to desolate-basin-50546.


can someone help  me
