### ISSUE TITLE
error: ‘eio_req’ has not been declared

### ISSUE THREAD

**Issue by tk120404** [peterbraden/node-opencv#41]
Hi 

Getting the following error on installation

CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:4:0:
../src/CascadeClassifierWrap.h:16:35: error: ‘eio_req’ has not been declared
../src/CascadeClassifierWrap.h:17:39: error: ‘eio_req’ has not been declared
make: *** [Release/obj.target/opencv/src/init.o] Error 1

**Comment by danschultzer** [comment]
This issue looks like it's no longer relevant. We're well beyond node 0.10, and a lot of changes has happened to `node-opencv` since.
