### ISSUE TITLE
Template match methods: Accept matrix

### ISSUE THREAD

**Issue by strarsis** [peterbraden/node-opencv#420]
Sometimes a template image has to be matched multiple times.
The current implementations of the template matching methods expect [a file path](https://github.com/peterbraden/node-opencv/issues/417#issuecomment-226909556).

Passing a matrix (e.g. from readImage(...)) as argument will not work and 
results in an (unrelated) assertion failure.

Because the file data could actually come from many different places and through different ways, 
it would make more sense to remove the path loading feature from the template matching methods 
and rather let them exclusively accept a matrix instead.

**Comment by Evilcat325** [comment]
+1 for this.
I haven't write any c++ for years, and might look in to write some when I pick it backup.
I think the matchTemplate should be able to accept a buffer or a matrix.
Having a method that can only read from file system really defect all the purpose by using a C++ library. 
In my case, I am trying to waiting for a image to show up on a certain website. The only way to do it now is to save the 'template' as a png on the filesystem to match. It would be much better to save it in the memory and use when the function get called. 

Also a big downside for not able to accept matrix or a buffer is that we cannot first process the image then matchTemplate it. If I want to convert to grayscale or do canny edge then matchtemplate to reduce the possibility of false positive, right now we need to first write to a file then passing it to the c++ library

**Comment by strarsis** [comment]
@Evilcat325: This may be of course only a workaround - but you could try using a ramdisk for the saving/loading image part.

**Comment by Evilcat325** [comment]
I just submit a pull request with unit test, hope it get merged~
