### ISSUE TITLE
question

### ISSUE THREAD

**Issue by smolleyes** [peterbraden/node-opencv#422]
hi

is it possible to reproduce this process with this library ?

http://people.csail.mit.edu/talidekel/papers/RBNR.pdf

(not the lastest step with tesseract...)

thanks !

**Comment by bradrisse** [comment]
So you want to first detect if there is a runner is in the image, you can do this using the face detection. After detecting a face, you know that the number tag on the runner is below. You can then detect the rectangle shape of the tag. Combine that with https://www.npmjs.com/package/node-tesseract and you can now get the tag number.

**Comment by danschultzer** [comment]
This question should be posted at stackoverflow, or the opencv forum. This library is `opencv` bindings for node.js.
