### ISSUE TITLE
intall error [C2872 type_info:ambiguous symbol]

### ISSUE THREAD

**Issue by illfar** [peterbraden/node-opencv#426]
I want to intall opencv in my project.
I have done the following steps.
1.install opencv-2.4.13.exe
2.set up the [OPENCV_PATH] and path (%OPENCV_DIR%\bin)
 my PC is not X64, so I set the [OPENCV_PATH] as [opencv\build\x86\vc12]
3.in my project DIR and execute the [npm intall opencv]
  and the following error is occoured. and I modified the any.h
 [std::type_info  ] to [type_info].

but now the[C2872 type_info:ambiguous symbol] is happened.

----------------------------------------------------------------------------------------------
c:\t-shirt\opensource\opencv\opencv\build\include\opencv2\flann\any.h(60): erro
r C2872: 'type_info' : ambiguous symbol (..\src\VideoCaptureWrap.cc) [C:\T-shir
t\SourceCode\FromRCL\tshirtdesigner-win32-ia32\resources\app\node_modules\openc
v\build\opencv.vcxproj]
          could be 'C:\Program Files\Visual Studio 2013\VC\include\typeinfo(44)
   : type_info'
          or       'c:\t-shirt\sourcecode\fromrcl\tshirtdesigner-win32-ia32\res
  ources\app\node_modules\opencv\src\OpenCV.h(9) : std::type_info'
----------------------------------------------------------------------------------------------

How can I resolved this problem?

**Comment by ChaloZ23** [comment]
Hi,
Follow these instructions: [https://github.com/peterbraden/node-opencv/issues/382](url)

NOTE: You must download the package indicated in the post and run "npm install" inside the directory unziped.

**Comment by illfar** [comment]
I have resolved this problem by th following way.
--------------------------------------
OpenCV.h

#ifdef WIN
    /*
        This is needed on Windows for Visual Studio to not throw an error in the
        build/include/opencv2/flann/any.h file in OpenCV.
    */
    //namespace std{ typedef type_info type_info; }    ---->comment out
#endif

-------------------------------------------------------
opencv is installed in my project 's node_modules folder.
but now npm start my project , another error happend.
------------------
my index.js
const cv = require('opencv');
------------------
error: can't find module. ...opencv\build\opencv\v5.0.0\Release\node-v48-win32-ia32\opencv.node

this file is builded ,but error is yet happened.
