### ISSUE TITLE
installed, cannot find module [opencv] in electron platform(#426)

### ISSUE THREAD

**Issue by illfar** [peterbraden/node-opencv#430]
(#426)'s next...

In my electron project , I installed opencv and the opencv is exist in the [node_modules].
and I add the [var cv = require('opencv');] in electron's index.js.
but [npm start]

the following error is occured.(the following file is exist,too)

Cannot find module
'C:\.....\node_modules\opencv\build\opencv\v5.0.0\Release\node-v47-win32-ia32\opencv.node'

**Comment by danschultzer** [comment]
I had similar issue, and it's because of `node-pre-gyp`. It resolves to a different build version than what has been compiled in electron. I've added #437 PR to fix it (you can try pull directly from that branch in package.json to test it out).
