### ISSUE TITLE
fail to install opencv in win7

### ISSUE THREAD

**Issue by kikaendeavor** [peterbraden/node-opencv#432]
I got the error log below~.
who would like to give me a hand?

`$ npm install opencv -save

> opencv@5.0.0 install D:\work\scan-dial\node_modules\opencv
> node-pre-gyp install --fallback-to-build

D:\work\scan-dial\node_modules\opencv>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )

D:\work\scan-dial\node_modules\opencv>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=D:\work\scan-dial\node_modules\opencv\build\opencv\v5.0.0\Release\node-v14-win32-ia32\opencv.node --module_name=opencv --module_path=D:\work\scan-dial\node_modules\opencv\build\opencv\v5.0.0\Release\node-v14-win32-ia32 )  else (node  configure --fallback-to-build --module=D:\work\scan-dial\node_modules\opencv\build\opencv\v5.0.0\Release\node-v14-win32-ia32\opencv.node --module_name=opencv --module_path=D:\work\scan-dial\node_modules\opencv\build\opencv\v5.0.0\Release\node-v14-win32-ia32 )

D:\work\scan-dial\node_modules\opencv>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=D:\work\scan-dial\node_modules\opencv\build\opencv\v5.0.0\Release\node-v14-win32-ia32\opencv.node --module_name=opencv --module_path=D:\work\scan-dial\node_modules\opencv\build\opencv\v5.0.0\Release\node-v14-win32-ia32 )  else (node  build --fallback-to-build --module=D:\work\scan-dial\node_modules\opencv\build\opencv\v5.0.0\Release\node-v14-win32-ia32\opencv.node --module_name=opencv --module_path=D:\work\scan-dial\node_modules\opencv\build\opencv\v5.0.0\Release\node-v14-win32-ia32 )
▒ڴ˽▒▒▒▒▒▒▒▒һ▒▒▒▒▒▒һ▒▒▒▒Ŀ▒▒▒▒Ҫ▒▒▒ò▒▒▒▒▒▒ɣ▒▒▒▒▒ӡ▒/m▒▒▒▒▒ء▒
D:\work\scan-dial\node_modules\opencv\build\opencv.vcxproj(19,3): error MSB4019: δ▒ҵ▒▒▒▒▒▒▒▒Ŀ▒▒D:\Microsoft.Cpp.Default.props▒▒▒▒▒▒ȷ▒▒ <Import> ▒▒▒▒▒е▒·▒▒▒▒ȷ▒▒▒Ҵ▒▒▒▒ϴ▒▒ڸ▒▒ļ▒▒▒
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\work\\scan-dial\\node_modules\\opencv\\build\\opencv\\v5.0.0\\Release\\node-v14-win32-ia32\\opencv.node" "--module_name=opencv" "--module_path=D:\\work\\scan-dial\\node_modules\\opencv\\build\\opencv\\v5.0.0\\Release\\node-v14-win32-ia32"
gyp ERR! cwd D:\work\scan-dial\node_modules\opencv
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\work\scan-dial\node_modules\opencv\build\opencv\v5.0.0\Release\node-v14-win32-ia32\opencv.node --module_name=opencv --module_path=D:\work\scan-dial\node_modules\opencv\build\opencv\v5.0.0\Release\node-v14-win32-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\work\scan-dial\node_modules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "D:\\work\\scan-dial\\node_modules\\opencv\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\work\scan-dial\node_modules\opencv
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\work\scan-dial\node_modules\opencv\build\opencv\v5.0.0\Release\node-v14-win32-ia32\opencv.node --module_name=opencv --module_path=D:\work\scan-dial\node_modules\opencv\build\opencv\v5.0.0\Release\node-v14-win32-ia32' (1)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "opencv" "-save"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! opencv@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@5.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\work\scan-dial\npm-debug.log
`

**Comment by jgcoding** [comment]
I am experiencing the same issue described by @kikaendeavor. 

(partial log file beginning just prior the first error:

63 silly lifecycle opencv@5.0.0~install: Args: [ '/d /s /c', 'node-pre-gyp install --fallback-to-build' ]
64 silly lifecycle opencv@5.0.0~install: Returned: code: 1  signal: null
65 info lifecycle opencv@5.0.0~install: Failed to exec install script
66 verbose stack Error: opencv@5.0.0 install: `node-pre-gyp install --fallback-to-build`
66 verbose stack Exit status 1
66 verbose stack     at EventEmitter.<anonymous> (C:\Users\Mac\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:233:16)
66 verbose stack     at emitTwo (events.js:87:13)
66 verbose stack     at EventEmitter.emit (events.js:172:7)
66 verbose stack     at ChildProcess.<anonymous> (C:\Users\Mac\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
66 verbose stack     at emitTwo (events.js:87:13)
66 verbose stack     at ChildProcess.emit (events.js:172:7)
66 verbose stack     at maybeClose (internal/child_process.js:827:16)
66 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
67 verbose pkgid opencv@5.0.0
68 verbose cwd C:\Users\Mac\Documents\Development\Balzano\node-opencv
69 error Windows_NT 10.0.14393
70 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mac\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
71 error node v4.4.7
72 error npm  v3.3.9
73 error code ELIFECYCLE
74 error opencv@5.0.0 install: `node-pre-gyp install --fallback-to-build`
74 error Exit status 1
75 error Failed at the opencv@5.0.0 install script 'node-pre-gyp install --fallback-to-build'.
75 error This is most likely a problem with the opencv package,
75 error not with npm itself.
75 error Tell the author that this fails on your system:
75 error     node-pre-gyp install --fallback-to-build
75 error You can get their info via:
75 error     npm owner ls opencv
75 error There is likely additional logging output above.
76 verbose exit [ 1, true ]

**Comment by jgcoding** [comment]
@kikaendeavor - I was able to successfully build and install by adding these steps to those provided:

1) Open terminal/cli to the project root
2) run 'npm i -g node-gyp' and 'npm i -g node-pre-gyp'
3) run 'npm install opencv'

4) In the consuming/target application into which opencv is to be installed, run 'npm i --save node-gyp node-pre-gyp'

5) finally, run 'npm i --save opencv'

Following those additional steps fixed the build and the installation for me.


    "opencv": "^5.0.0",

**Comment by kikaendeavor** [comment]
@jgcoding 3Q for guide, but I'm still fail to installing.
the same error from gyp, it's a pity

**Comment by kikaendeavor** [comment]
I installed successful in Ubuntu 12, so let win7 go.
