### ISSUE TITLE
car model detection

### ISSUE THREAD

**Issue by tadjik1** [peterbraden/node-opencv#434]
Hi there!

I want to make a simple application for detecting car model by photo. I'm newbie in this sphere (I'm frontend developer) - but it's very interesting for me. Help me please to find information about how could I do it.

**Comment by danschultzer** [comment]
This is not the right place to ask for that, you should go to stackoverflow or the opencv forum. You can find the example in the source code: https://github.com/peterbraden/node-opencv/blob/master/examples/car-detection.js
