### ISSUE TITLE
how to recognize numbers from an image?

### ISSUE THREAD

**Issue by kikaendeavor** [peterbraden/node-opencv#435]
this is the origin picture 
![2016-08-26_224809](https://cloud.githubusercontent.com/assets/2987889/18025470/59404dc6-6c5d-11e6-8e45-f48d3dc1ddbf.png)

I converted it by node-opencv
![2016-08-26_225113](https://cloud.githubusercontent.com/assets/2987889/18025472/6368f884-6c5d-11e6-9ab6-6ac0d518ae22.png)

now I want to get the number as text, how to call KNN or some other functions?
Any help is appreciate.

**Comment by danschultzer** [comment]
Why not use tesseract instead? If you really want to use opencv then I think [scene text](http://docs.opencv.org/3.0-beta/modules/text/doc/erfilter.html) might be what you need. But you should ask this question on stackoverflow, or the opencv forum instead.
