### ISSUE TITLE
matchTemplate: Reduce/increase channels

### ISSUE THREAD

**Issue by strarsis** [peterbraden/node-opencv#436]
The "base" matrix has got 4 channels (PNG with alphatransparency) and 
the second image (JPG without any transparency) which is passed to matchTemplate(...) got 3 channels.
````
OpenCV Error: Assertion failed ((img.depth() == CV_8U || img.depth() == CV_32F) && img.type() == templ.type())[...]
````

In my opinion should node-opencv take this into account and add an extra channel to the other matrix.

Is there a workaround where I can add a dummy/empty alphatransparency channel to node-opencv matrix?

**Comment by danschultzer** [comment]
I don't think `matchTemplate` [handles alpha channel](https://github.com/opencv/opencv/issues/4726), and in any case, the API in node-opencv should be identical to the API in opencv.

**Comment by danschultzer** [comment]
From the discussion in https://github.com/lovell/sharp/issues/534#issuecomment-246780955, I'll assume this has been resolved. Closing it for now.

**Comment by strarsis** [comment]
One can also use Matrix split()+merge(...) methods to remove an alpha channel of a matrix 
so both both matrices got equal channel count.
