### ISSUE TITLE
Loading a PNG drops the alpha channel

### ISSUE THREAD

**Issue by Nateowami** [peterbraden/node-opencv#440]
When I load a PNG image only 3 channels are loaded into the matrix:
``` javascript
cv.readImage('path/to/image.png', function(err, img){
  if(err) throw err;
  console.log(img.channels()); // Prints '3'
  img.save('out.png');
});
```
When the file is saved, it is saved without an alpha channel. Looking at the source code for [OpenCV.cc](https://github.com/peterbraden/node-opencv/blob/0374115c729f6ca124fb61576b274e4188dd38e9/src/OpenCV.cc#L40) I see the image is loaded with `cv::imread(filename, CV_LOAD_IMAGE_UNCHANGED)`. I understood from other sources that `CV_LOAD_IMAGE_UNCHANGED` should preserve the alpha channel.

**Comment by danschultzer** [comment]
In package.json load from master:
```json
"opencv": "peterbraden/node-opencv"
```

CV_LOAD_IMAGE_UNCHANGED was merged in [back in may](https://github.com/peterbraden/node-opencv/pull/405), but there's not been a new release yet.

**Comment by Nateowami** [comment]
@danschultzer Ah, I see. Thanks. Should have checked the git blame. Is the master branch pretty stable then, or is it better to select a specific commit?

**Comment by danschultzer** [comment]
Yeah, the master branch has been pretty stable for me.
