### ISSUE TITLE
Is Face Recognition ( Eigenfaces , etc ) Supported ?

### ISSUE THREAD

**Issue by gedeagas** [peterbraden/node-opencv#442]
Hi, i just want to ask if Face Recognition ( Eigenfaces , etc ) is supported ?

**Comment by danschultzer** [comment]
[Yeah](https://github.com/peterbraden/node-opencv/blob/master/src/FaceRecognizer.h), there's support for eigen, lbph and fisher. There's an example here, though it's just in a comment: 

https://github.com/peterbraden/node-opencv/blob/ead733ba3410ed6112ba6e19552c99db2d21359c/smoke/smoketest.js
