### ISSUE TITLE
Release 6.0.0

### ISSUE THREAD

**Issue by danschultzer** [peterbraden/node-opencv#443]
Here's the current full diff: https://github.com/peterbraden/node-opencv/compare/5fb426aa1428b3d16e7fb0b1412f44410077382e...master

New methods:
`contour.points`
`matrix.moments`
`matrix.mean`
`matrix.subtract `

Breaking changes: #405 #444

This will resolve #386 #392

I'll check all issues and PR, and prioritize the ones that should make it to 6.0.0.

**Comment by peterbraden** [comment]
I added #428 and #444, let me know if there's any objections or I can probably do the release today

**Comment by danschultzer** [comment]
👍 Actually I've been working on adding in code coverage today, but lcov was causing a lot of trouble. Finally got it sorted out: #445

**Comment by danschultzer** [comment]
Let's continue this in #446 where we have the full CHANGELOG.
