### ISSUE TITLE
Use of DEBUG environment variable clashes with the debug module

### ISSUE THREAD

**Issue by jwagner** [peterbraden/node-opencv#452]
The [debug](https://www.npmjs.com/package/debug) node module uses the environment variable `DEBUG` to toggle debug statements. node-opencv uses the mere presence of same environment variable to toggle a debug mode:

```
var binding_path = binary.find(path.resolve(path.join(__dirname,'../package.json')), { debug: !!process.env.DEBUG });
```

The two obviously collide. Given that the debug module is used by over 10'000 modules I think this should be resolved on the node-opencv side.

In my case this lead to a failure in production where some debug statements were on. Things passed fine in staging and ci where no debug logging was turned on. 

As far as I see it there are two ways of addressing this issue:
A) Checking for the presence of a specific value in the debug flag to be compatible with the usage of the debug module
B) Using a more specific environment variable such as NODE_OPENCV_DEBUG

I'd personally prefer option B, but this is of course up to you to decide.

**Comment by danschultzer** [comment]
It was introduced with the code coverage PR: #445 

There's no problem changing the environment variable, so let's go for option B.
