### ISSUE TITLE
Find blob location

### ISSUE THREAD

**Issue by andrewda** [peterbraden/node-opencv#454]
Assuming I have an image returned by the `inRange()` method, such as the image below, how would I go about finding the pixel location of the blob? In OpenCV Python and C++, there are many tutorials that go over this, such as [this one](https://www.learnopencv.com/blob-detection-using-opencv-python-c/), but I can't figure out how to go about this using node-opencv. Could someone please shed some light?

![coin_detected](https://cloud.githubusercontent.com/assets/10191084/19545763/e8a709d2-963d-11e6-9997-d639c330c857.jpg)

**Comment by rafis** [comment]
I think this is not implemented.

SimpleBlobDetector - not implemented
KeyPoint struct - not implemented
Other Feature2D module features - not implemented.

Seems currently node-opencv orients more towards video processing, not image processing.

**Comment by andrewda** [comment]
Alright. Hopefully I can come back to node-opencv when more features are implemented, but for now I think I'll use Python.
