### ISSUE TITLE
examples/dissimilarity.js doesn't work

### ISSUE THREAD

**Issue by rafis** [peterbraden/node-opencv#456]
**OS:** Windows 7 x64 latest

examples/dissimilarity.js returns empty output. It halts silently on this line:

    cv.ImageSimilarity(car1, car2, function (err, dissimilarity) {

Other examples seems to be working.

**Comment by rafis** [comment]
This is related to:
http://stackoverflow.com/questions/14453541/opencv-c-crashes-on-close
http://stackoverflow.com/questions/31290558/how-to-find-the-error-program-crash-after-executing-quit-sequence-python-open

Thus it is not related to `peterbraden/node-opencv`.

**Comment by bmathews** [comment]
I'm having the same issue. ImageSimilarity silently crashes, and most other examples work, but not all. @rafis did you have any figuring this out?
