### ISSUE TITLE
Are the calls to opencv synchronous?

### ISSUE THREAD

**Issue by IonicaBizau** [peterbraden/node-opencv#468]
I'm make a lot of async calls, but it looks like they are executed one after another, like a queue, therefore the performance is quite slow (on a fast computer).

Is it possible that the calls to opencv are somehow synchronous or something like that?

**Comment by tomorrowthief** [comment]
你用的电脑型号是什么？

**Comment by IonicaBizau** [comment]
> What computer model you use?

@tomorrowthief I use an ASUS machine, with Intel Core i7 processor, 16GB RAM and 120GB SSD.

**Comment by IonicaBizau** [comment]
@peterbraden Why was this closed...?
