### ISSUE TITLE
Installation and Use On Raspberry Pi

### ISSUE THREAD

**Issue by pdr0663** [peterbraden/node-opencv#476]
I am struggling to get NPM OpenCV to work on a Raspberry Pi.

Firstly, NPM OpenCV requires node.js version 0.12 or better. I managed to uninstall the standard 0.10.X version which is installed by default in Pixel, and install NVM and 0.12.17. It seems to work ok.

Secondly, OpenCV installed in Pixel is version 2.4.9, which qualifies ok according to NPM OpenCV. However, NPM OpenCV failed with an error which seemed to indicate that OpenCV could not be found. I downloaded and compiled my own copy of OpenCV, version 2.4.13. This compiled ok with the default ccmake settings. NPM OpenCV then installed satisfactorily.

The problem I now have, is that require("OpenCV") fails, and I can't find out why. Here is the output from node when I try to run either my software, or the examples...

```
pi@raspberrypi:~/js/opencv $ node opencv.js
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: libopencv_gpu.so.2.4: cannot open shared object file: No such file or directory
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/node_modules/opencv/lib/bindings.js:5:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

```

I'm not familiar with debugging node modules, and "module.js" I can't find. Bindings.js I can find, and also tries to "require" something, and that something is a binary file, so my debugging ends there...

Any help greatly appreciated.

Regards,

Paul

**Comment by alberto2000** [comment]
I'm also very interested in running it on a Pi - I've been as far as I got on MacOs: been able to install the package although the node-pre-gyp errors popped and lots of warnings, but it finished installing at least. But then require('opencv') throws an error - mine was something about a path mismatch in the node module folder...

**Comment by sergei202** [comment]
@pdr0663: If you're using the latest version of Raspbian, you should be able to just install `libopencv-dev`:

```sudo apt-get install libopencv-dev```

It worked for me from a fresh install.  Let me know if that helps!

**Comment by pdr0663** [comment]
Sergei,

Thanks for your advice. I did that before reading your post, and came here to advise that it was successful. Thanks anyway for the tip!

One small problem, when I require("opencv") it can't find it. Had to enter the full path to the NPM opencv folder... I installed opencv with "-g", would that make a difference?

Paul

**Comment by sergei202** [comment]
@pdr0663:

Installing with `-g` will install a package globally, but that's usually only used for tools like `bower` or others with executables.  `opencv` doesn't have any (that I know of at least), so you don't need to install it globally.

You should only have to `npm install opencv` from the root of your project and node will automatically find out with `require('opencv')` without having to give it a full path.

**Comment by pdr0663** [comment]
Sergei,

Many thanks again. Uninstalled and installed as you recommend, works fine. Happy now. Will get to play!

Paul

**Comment by sergei202** [comment]
Glad to help!  Don't forget to close the issue if you're all set :smile:
