### ISSUE TITLE
node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by xStarman** [peterbraden/node-opencv#478]
I have the following error while trying to install:
`$ npm install opencv --save

> opencv@6.0.0 install D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\open                                                                                                                cv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/o                                                                                                                pencv/v6.0.0/Release/node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@6.9.2 (                                                                                                                node-v48 ABI) (falling back to source compile with node-gyp)

D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\opencv>if not defined npm_c                                                                                                                onfig_node_gyp (node "C:\Users\Pessoal\AppData\Roaming\npm\node_modules\node_mod                                                                                                                ules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )                                                                                                                  else (node "" clean )

D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\opencv>if not defined npm_c                                                                                                                onfig_node_gyp (node "C:\Users\Pessoal\AppData\Roaming\npm\node_modules\node_mod                                                                                                                ules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configur                                                                                                                e --fallback-to-build "--module=D:\Arquivos Pessoal\Desktop\dev\test nw\node_mod                                                                                                                ules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node" --module                                                                                                                _name=opencv "--module_path=D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules                                                                                                                \opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64" --python=C:\Python27 --m                                                                                                                svs_version=2015 )  else (node "" configure --fallback-to-build "--module=D:\Arq                                                                                                                uivos Pessoal\Desktop\dev\test nw\node_modules\opencv\build\opencv\v6.0.0\Releas                                                                                                                e\node-v48-win32-x64\opencv.node" --module_name=opencv "--module_path=D:\Arquivo                                                                                                                s Pessoal\Desktop\dev\test nw\node_modules\opencv\build\opencv\v6.0.0\Release\no                                                                                                                de-v48-win32-x64" --python=C:\Python27 --msvs_version=2015 )

D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\opencv>if not defined npm_c                                                                                                                onfig_node_gyp (node "C:\Users\Pessoal\AppData\Roaming\npm\node_modules\node_mod                                                                                                                ules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --                                                                                                                fallback-to-build "--module=D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules                                                                                                                \opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node" --module_nam                                                                                                                e=opencv "--module_path=D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\ope                                                                                                                ncv\build\opencv\v6.0.0\Release\node-v48-win32-x64" )  else (node "" build --fal                                                                                                                lback-to-build "--module=D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\op                                                                                                                encv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node" --module_name=o                                                                                                                pencv "--module_path=D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\opencv                                                                                                                \build\opencv\v6.0.0\Release\node-v48-win32-x64" )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\opencv\build\opencv.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Pessoal\AppData\Roaming\npm\node_modules\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Pessoal\\AppData\\Roaming\\npm\\node_modules\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\Arquivos Pessoal\\Desktop\\dev\\test nw\\node_modules\\opencv\\build\\opencv\\v6.0.0\\Release\\node-v48-win32-x64\\opencv.node" "--module_name=opencv" "--module_path=D:\\Arquivos Pessoal\\Desktop\\dev\\test nw\\node_modules\\opencv\\build\\opencv\\v6.0.0\\Release\\node-v48-win32-x64"
gyp ERR! cwd D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\opencv
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Arquivos Pessoal\\Desktop\\dev\\test nw\\node_modules\\opencv\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\opencv
node-pre-gyp ERR! node -v v6.9.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64' (1)
npm WARN Invalid version: "1"
npm WARN test nw No description
npm WARN test nw No repository field.
npm WARN test nw No README data
npm WARN test nw No license field.
npm WARN In opencv@6.0.0 replacing bundled version of node-pre-gyp with node-pre-gyp@0.6.32
npm WARN Error: EPERM: operation not permitted, lstat 'D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\tar-pack\node_modules'
npm WARN     at Error (native)
npm WARN  { Error: EPERM: operation not permitted, lstat 'D:\Arquivos Pessoal\Desktop\dev\test nw\node_modules\tar-pack\node_modules'
npm WARN     at Error (native)
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'lstat',
npm WARN   path: 'D:\\Arquivos Pessoal\\Desktop\\dev\\test nw\\node_modules\\tar-pack\\node_modules' }
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Pessoal\\AppData\\Roaming\\npm\\node_modules\\node_modules\\npm\\bin\\npm-cli.js" "install" "opencv" "--save"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Arquivos Pessoal\Desktop\dev\test nw\npm-debug.log

Pessoal@Pessoal-PC MINGW64 /d/Arquivos Pessoal/Desktop/dev/test nw
`

npm-debug.log:
[npm-debug.txt](https://github.com/peterbraden/node-opencv/files/691835/npm-debug.txt)

System configs: 

windows 7 x64

$ node -v
v6.9.2

$ npm -v
4.0.5

$ node-gyp -v
v3.4.0

$ node-pre-gyp -v
v0.6.32

**Comment by prydin** [comment]
I'm seeing a similar issue on CentOS 7:

> opencv@6.0.0 install /node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@6.9.1 (node-v48 ABI) (falling back to source compile with node-gyp) 
/node_modules/opencv/utils/find-opencv.js:21
                throw new Error("ERROR: failed to run: pkg-config", opencv, flag);
                ^

Error: ERROR: failed to run: pkg-config
    at /node_modules/opencv/utils/find-opencv.js:21:23
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp: Call to 'node utils/find-opencv.js --cflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.0-229.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/node_modules/opencv/build/opencv/v6.0.0/Release/node-v48-linux-x64/opencv.node" "--module_name=opencv" "--module_path=/node_modules/opencv/build/opencv/v6.0.0/Release/node-v48-linux-x64"
gyp ERR! cwd /node_modules/opencv
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/node_modules/opencv/build/opencv/v6.0.0/Release/node-v48-linux-x64/opencv.node --module_name=opencv --module_path=/node_modules/opencv/build/opencv/v6.0.0/Release/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 3.10.0-229.el7.x86_64
node-pre-gyp ERR! command "/usr/bin/node" "/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /node_modules/opencv
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/node_modules/opencv/build/opencv/v6.0.0/Release/node-v48-linux-x64/opencv.node --module_name=opencv --module_path=/node_modules/opencv/build/opencv/v6.0.0/Release/node-v48-linux-x64' (1)
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.
npm WARN In opencv@6.0.0 replacing bundled version of node-pre-gyp with node-pre-gyp@0.6.32
npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "opencv"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

**Comment by haipz** [comment]
+1

**Comment by BrianLenzo** [comment]
We are behind a corporate proxy and having trouble pulling down this tarball.  Is there a place we could have developers put this archive manually so it would not try to download it and fail?

**Comment by hanalaydrus** [comment]
Got the same problem on windows, mine is
1. Node 6.2.2
2. Visual Studio 2017 
3. OpenCV 2.4.13.2 (vc14)
you can get it here 
[](https://github.com/opencv/opencv/releases/download/2.4.13.2/opencv-2.4.13.2-vc14.exe)

And for the installation, this is the steps i took.
1. Create a system variable called `OPENCV_DIR` and set it to `C:\OpenCV\build\x64\vc14`
2. Also add the following to your system `PATH` `;%OPENCV_DIR%\bin`
3. Download peterbraden/node-opencv fork git clone [](https://github.com/peterbraden/node-opencv)
4. Run npm install with `npm install opencv --build-from-source`

**Comment by hanalaydrus** [comment]
Got the same problem on windows and solved, mine is
1. Node 6.2.2
2. Visual Studio 2017 
3. OpenCV 2.4.13.2 (vc14)
you can get it here 
https://github.com/opencv/opencv/releases/download/2.4.13.2/opencv-2.4.13.2-vc14.exe

And for the installation, this is the steps i took.
1. Create a system variable called `OPENCV_DIR` and set it to `C:\OpenCV\build\x64\vc14`
2. Also add the following to your system `PATH` `;%OPENCV_DIR%\bin`
3. Download peterbraden/node-opencv fork git clone https://github.com/peterbraden/node-opencv
4. Run npm install with `npm install opencv --build-from-source`

**Comment by davae1an** [comment]
@hanalaydrus 

Thanks to you i got it fixed. No need for Visual Studio just install windows build tools 

 `npm install --global --production windows-build-tools`
