### ISSUE TITLE
Memory Leak in findContours

### ISSUE THREAD

**Issue by vpanichkin** [peterbraden/node-opencv#504]
I have found a memory Leak in findContours
Here is the test application, that breaks down...

`var cv = require('opencv');

var func = function() {
    cv.readImage('./public/images/live.png', function (err, im) {
        im.canny(100,1000);
        var contours = im.findContours();
        im.release();
    });
};

for(var i = 0; i < 100;i++){
    func();
    console.log(i);
}`

Exit with error...
![1](https://cloud.githubusercontent.com/assets/16993030/25898313/53b3b298-3594-11e7-9e5f-bb653fe9d0b6.PNG)

Can someone fix this or suggest the release method for contours. Thanks!

**Comment by chebuRush** [comment]
Hmm..Find out that bug causes in node v.6.3.10 .

[Solve] Reinstall node v4.8.3. Everything works fine.
