### ISSUE TITLE
Ability to change resolution of captured image

### ISSUE THREAD

**Issue by timfpark** [peterbraden/node-opencv#53]
First off, thanks for writing node-opencv - great package to use so far.

I can't seem to find a way to change the resolution of the captured image using VideoCapture - is there a way that I'm missing to set the resolution of the images that are captured by the camera?   By default, i'm getting image matrices of 160x120 which obviously is lower than ideal.

Many apologies in advance if this is obvious and I missed it in one of the examples or docs.

**Comment by danschultzer** [comment]
You can set width/height with `setWidth` and `setHeight`:

https://github.com/peterbraden/node-opencv/blob/ead733ba3410ed6112ba6e19552c99db2d21359c/src/VideoCaptureWrap.h#L20-L22

```
  // (Optional) For setting width and height of the input video stream
  static NAN_METHOD(SetWidth);
  static NAN_METHOD(SetHeight);
```
