### ISSUE TITLE
Amazon path: node-v57-darwin-x64.tar.gz is 403

### ISSUE THREAD

**Issue by webber-naut** [peterbraden/node-opencv#538]
Seems your Amazon link/account for the download in your script is a 403.

`node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v57-darwin-x64.tar.gz`

Please fix this or move file to new location so we can update the package.json

Thanks.

**Comment by thuydao** [comment]
i have the same issue

**Comment by peterbraden** [comment]
This should now be fixed,.
