### ISSUE TITLE
Get dominant color from image 

### ISSUE THREAD

**Issue by muhammadsamir11** [peterbraden/node-opencv#541]
Hi I wonder if anyone can help me to get the dominant color using node opencv

**Comment by piercus** [comment]
I would suggest you to use "calcHist", implemented on PR #536 

On my branch, you will find examples in https://github.com/piercus/node-opencv/blob/master/examples/calc-hist.js

With the histogram, you will be able to see the distribution of values.

On a 256-values + 3 channels , you have 16M colors.

I think this is too much, so i would suggest you split this 3 dimensions space into bigger changes.

If you want to work with 64 colors, that's the idea i have used in https://github.com/piercus/colorfulness  and https://github.com/piercus/node-opencv/blob/master/examples/emd.js implementations

So to get dominant color between 64 (= 4*4*4) colors, you will do like

```javascript
    // im1 is an opencv Matrix
    var bins = 4,
        size = [bins, bins, bins],
        channels = [0, 1, 2],
        range = [[0, 256], [0, 256], [0, 256]],
        uniform = true;

    /// Compute 64 (=bins^3) histograms:
    var ImageHist = cv.histogram.calcHist(im1, channels, size, range, uniform);
     
    var max = 0;
    var maxColor = null;
    var step = 256/bins;
    var halfStep = step/2;

    ImageHist.map(function(bHist, bIndex){
      return bHist.map(function(bgHist, gIndex){
        return bgHist.map(function(bgrHist, rIndex){
          if(bgrHist > max) {
            max = bgrHist; 
            maxColor = [bIndex*step+halfStep, gIndex*step+halfStep, rIndex*step+halfStep];
          }
        })
      })
    })
    
    // max Color is "dominant" color in BGR notation
```

you can change `size`to change the granularity of your calculation.

Disclaimer : i did not run this code locally
