### ISSUE TITLE
node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by davidplappert** [peterbraden/node-opencv#543]
I've been fighting this for a couple days. I've used Amazon Linux, Ubuntu 16.04 LTS, and My macbook, all with the same output when I run:
`npm install opencv`

The biggest concern is when I installed opencv on Ubuntu 16.04 LTS Server, like this:
`apt-get install libopencv-dev` I still got the below error.

Any help is greatly appreciated.

```
root@ip-172-26-5-128:~/processImagesForFacialRecognition# npm install opencv

> opencv@6.0.0 install /root/processImagesForFacialRecognition/node_modules/opencv
> node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: Permission denied
npm WARN processimagesforfacialrecognition@1.0.0 No description
npm WARN processimagesforfacialrecognition@1.0.0 No repository field.
npm WARN In opencv@6.0.0 replacing bundled version of node-pre-gyp with node-pre-gyp@0.6.36
npm ERR! Linux 4.4.0-1013-aws
npm ERR! argv "/root/.nvm/versions/node/v6.11.3/bin/node" "/root/.nvm/versions/node/v6.11.3/bin/npm" "install" "opencv"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/processImagesForFacialRecognition/npm-debug.log

```

**Comment by piercus** [comment]
I see this : 
`sh: 1: node-pre-gyp: Permission denied`

Have you find anything on google related to this ?

**Comment by davidcarma** [comment]
Try running npm install as non root user if that is what you are doing.

**Comment by Vigor111** [comment]
but sudo npm install also doesn't work

**Comment by justadudewhohacks** [comment]
I sometimes faced this issue with node-pre-gyp when the project was opened in atom. Maybe you can also try to clean node_modules and reinstall.

**Comment by Vigor111** [comment]
but i just download the code from github and run the command
> npm install
and I faced that errors

**Comment by justadudewhohacks** [comment]
You could also try `npm install --unsafe-perm` or  `sudo npm install --unsafe-perm`.

**Comment by Vigor111** [comment]
It doesn't work

**Comment by ryangineer** [comment]
I am having the same exact problem. Can't install.

**Comment by peterbraden** [comment]
Can you paste the npm-debug.log?

**Comment by Vigor111** [comment]
[2017-09-13T10_10_39_350Z-debug.log.zip](https://github.com/peterbraden/node-opencv/files/1299050/2017-09-13T10_10_39_350Z-debug.log.zip)

**Comment by Lohann** [comment]
Same problem here

**Comment by Lohann** [comment]
That steps works for me on `MacOS Sierra 10.12.6`:
```
brew install opencv@2
brew unlink opencv@2 
brew link --overwrite opencv@2 --force
PKG_CONFIG_PATH="/usr/local/Cellar/opencv@2/2.4.13.2_2/lib/pkgconfig/"
npm install opencv
```

**Comment by misbah4064** [comment]
I'm having the same issue on Ubuntu. Worked well on Raspberry Pi and Windows.

**Comment by AndroConsis** [comment]
Worked for mac at last Thanks a lot

**Comment by Parameshvadivel** [comment]
https://github.com/peterbraden/node-opencv/issues/543#issuecomment-329487992
 still i did not able to install opencv

**Comment by jocbarbosa** [comment]
These commands worked like a charm for me on Ubuntu:

sudo npm cache clean -f
sudo npm install -g n
sudo n stable
sudo npm install --unsafe-perm=true --allow-root

**Comment by jeisux92** [comment]
> These commands worked like a charm for me on Ubuntu:
> 
> sudo npm cache clean -f sudo npm install -g n sudo n stable sudo npm install --unsafe-perm=true --allow-root

you just saved my life!

**Comment by formula21** [comment]
> sudo npm install --unsafe-perm=true --allow-root

You just saved my life & my job... Thanks man!!

**Comment by PedroAlvesM** [comment]
> These commands worked like a charm for me on Ubuntu:
> 
> sudo npm cache clean -f sudo npm install -g n sudo n stable sudo npm install --unsafe-perm=true --allow-root

Works!

**Comment by afotohi12** [comment]
> These commands worked like a charm for me on Ubuntu:
> 
> sudo npm cache clean -f sudo npm install -g n sudo n stable sudo npm install --unsafe-perm=true --allow-root

thanks man , thats work on ubuntu 22

**Comment by dev-vickie** [comment]
Worked in me too [ :heavy_check_mark: ]

**Comment by Prashanith** [comment]
Thanks man, I had issue installing bcrypt, Used those commands and it worked like a charm

**Comment by shenoysahana** [comment]
> These commands worked like a charm for me on Ubuntu:
> 
> sudo npm cache clean -f sudo npm install -g n sudo n stable sudo npm install --unsafe-perm=true --allow-root

Thank you so much. You saved my most of the time.

**Comment by lennybeadle** [comment]
did not work for me on mac

**Comment by rohit-rambade** [comment]
> These commands worked like a charm for me on Ubuntu:
> 
> sudo npm cache clean -f sudo npm install -g n sudo n stable sudo npm install --unsafe-perm=true --allow-root

Thank you so much
