### ISSUE TITLE
setting process.env.DEBUG breaks binding_path

### ISSUE THREAD

**Issue by tonila** [peterbraden/node-opencv#544]
We are using npm debug module, that uses process.env.DEBUG flag to define debug prints.

opencv uses process.env.DEBUG to define binding_path

Using debug with opencv triggers following error

`Error: Cannot find module '.../node_modules/opencv/build/opencv/v6.0.0/Debug/node-v57-linux-x64/opencv.node'`

That is because there is no Debug build. Only Release.

**Comment by skiloop** [comment]
It's fixed by PR:#453, but the fixed not in the latest 6.0.0
