### ISSUE TITLE
problem on building nodejs application in heroku server

### ISSUE THREAD

**Issue by rajabose** [peterbraden/node-opencv#546]
can someone help me please, I have been getting this error for a day whenever i just try to push my nodejs code to heroku server

remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=false
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  >=4.3 <7.0
remote:        engines.npm (package.json):   >=1.0.0
remote:
remote:        Resolving node version >=4.3 <7.0...
remote:        Downloading and installing node 6.11.3...
remote:        Bootstrapping npm >=1.0.0 (replacing 3.10.10)...
remote:        npm 5.4.2 installed
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (disabled)
remote:
remote: -----> Building dependencies
remote:        Prebuild detected (node_modules already exists)
remote:        Rebuilding any native modules
remote:
remote:        > uws@0.14.5 install /tmp/build_691c03bb9445cb4d916db850cd2f3fbd/node_modules/uws
remote:        > node-gyp rebuild > build_log.txt 2>&1 || exit 0
remote:
remote:
remote:        > v8-debug@1.0.1 preinstall /tmp/build_691c03bb9445cb4d916db850cd2f3fbd/node_modules/v8-debug
remote:        > node -e 'process.exit(0)'
remote:
remote:
remote:        > v8-debug@1.0.1 install /tmp/build_691c03bb9445cb4d916db850cd2f3fbd/node_modules/v8-debug
remote:        > node-pre-gyp install --fallback-to-build
remote:
remote:        sh: 1: node-pre-gyp: Permission denied
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 126
remote:        npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
remote:        npm ERR! Exit status 126
remote:        npm ERR!
remote:        npm ERR! Failed at the v8-debug@1.0.1 install script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /app/.npm/_logs/2017-09-23T09_19_33_695Z-debug.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:

**Comment by FindSunny** [comment]
@rajabose  try this [https://github.com/jansmolders86/mediacenterjs/issues/191](url)
