### ISSUE TITLE
Install instructions for Window do not work

### ISSUE THREAD

**Issue by johngrabner** [peterbraden/node-opencv#548]
Issue 1:
http://opencv.org/downloads.html is broken should be https://github.com/opencv/opencv/releases/tag/2.4.13.3 if 2.4 is the recommended target.

Issue 2:
C:\OpenCV\build\x64\vc12 does not exist, but C:\opencv\build\x64\vc14 does

Issue 3: 
Install Visual Studio 2013, but this will result in linking errors. LNK2038: mismatch _MSC_VER value 1900 does not match value 1800.  It appears 1800 refers to 2013 compiler, and 1900 refers to 2015 compiler.  So probably Visual studio 2015 should be installed.

Issue 4:
When visual studio 2015 is installed.  npn install opencv fails to compile.  Error indicates it can't find VCBuild.exe.  I'm stuck here. Can't find VCBuild in the visual studio directory, but I can compile cpp console programs.  So not sure if the compiler is a different name.

The following is the full console dump:

> opencv@6.0.0 install C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv
> node-pre-gyp install --fallback-to-build

C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean ) 

C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64 ) 

C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64 )  else (node "" build --fallback-to-build --module=C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64 ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv\build\binding.sln]
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\john_\Documents\GitHub\NodejsPnP\NodejsPnP\up_camera\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64' (1)

**Comment by johngrabner** [comment]
I found the following allowed my build to proceed.

# as admin
npm install --global --production windows-build-tools

I am not an expert and so am reluctant to update the documentation with this fix.

**Comment by nedol** [comment]
Did you manage to install opencv in node finally, I wonder? -  There is no problem with windows-build-tools  but opencv installation issue still exists for me.

**Comment by johngrabner** [comment]
A few months ago, I did install and it worked.



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by Aarul5** [comment]
@johngrabner  can you please guide me to install node-opencv, I got this error when i try to **install npm install opencv**

```

> opencv@6.0.0 install E:\2TEst\opencv\node_modules\opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/o
pencv/v6.0.0/Release/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@8.11.2
(node-v57 ABI, unknown) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  init.cc
  Matrix.cc
  OpenCV.cc
  CascadeClassifierWrap.cc
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\CascadeClassifierWrap.cc) [E:\2TEst\opencv\node_modules\opencv\buil
d\opencv.vcxproj]
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\OpenCV.cc) [E:\2TEst\opencv\node_modules\opencv\build\opencv.vcxpro
j]
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\Matrix.cc) [E:\2TEst\opencv\node_modules\opencv\build\opencv.vcxpro
j]
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\init.cc) [E:\2TEst\opencv\node_modules\opencv\build\opencv.vcxproj]
  Contours.cc
  Point.cc
  VideoCaptureWrap.cc
  CamShift.cc
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\Point.cc) [E:\2TEst\opencv\node_modules\opencv\build\opencv.vcxproj
]
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\VideoCaptureWrap.cc) [E:\2TEst\opencv\node_modules\opencv\build\ope
ncv.vcxproj]
  HighGUI.cc
  FaceRecognizer.cc
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\Contours.cc) [E:\2TEst\opencv\node_modules\opencv\build\opencv.vcxp
roj]
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\CamShift.cc) [E:\2TEst\opencv\node_modules\opencv\build\opencv.vcxp
roj]
  Features2d.cc
  BackgroundSubtractor.cc
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\HighGUI.cc) [E:\2TEst\opencv\node_modules\opencv\build\opencv.vcxpr
oj]
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\FaceRecognizer.cc) [E:\2TEst\opencv\node_modules\opencv\build\openc
v.vcxproj]
  Constants.cc
  Calib3D.cc
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\Features2d.cc) [E:\2TEst\opencv\node_modules\opencv\build\opencv.vc
xproj]
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\BackgroundSubtractor.cc) [E:\2TEst\opencv\node_modules\opencv\build
\opencv.vcxproj]
  ImgProc.cc
  Stereo.cc
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\Calib3D.cc) [E:\2TEst\opencv\node_modules\opencv\build\opencv.vcxpr
oj]
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\Constants.cc) [E:\2TEst\opencv\node_modules\opencv\build\opencv.vcx
proj]
  LDAWrap.cc
  win_delay_load_hook.cc
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\ImgProc.cc) [E:\2TEst\opencv\node_modules\opencv\build\opencv.vcxpr
oj]
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\Stereo.cc) [E:\2TEst\opencv\node_modules\opencv\build\opencv.vcxpro
j]
e:\2test\opencv\node_modules\opencv\src\OpenCV.h(19): fatal error C1083: Cannot
 open include file: 'opencv/cv.h': No such file or directory (compiling source
file ..\src\LDAWrap.cc) [E:\2TEst\opencv\node_modules\opencv\build\opencv.vcxpr
oj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:198:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallb
ack-to-build" "--module=E:\\2TEst\\opencv\\node_modules\\opencv\\build\\opencv\\
v6.0.0\\Release\\node-v57-win32-x64\\opencv.node" "--module_name=opencv" "--modu
le_path=E:\\2TEst\\opencv\\node_modules\\opencv\\build\\opencv\\v6.0.0\\Release\
\node-v57-win32-x64"
gyp ERR! cwd E:\2TEst\opencv\node_modules\opencv
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.j
s build --fallback-to-build --module=E:\2TEst\opencv\node_modules\opencv\build\o
pencv\v6.0.0\Release\node-v57-win32-x64\opencv.node --module_name=opencv --modul
e_path=E:\2TEst\opencv\node_modules\opencv\build\opencv\v6.0.0\Release\node-v57-
win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\2TEst\opencv\node_mo
dules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\2TEst\\open
cv\\node_modules\\opencv\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "instal
l" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\2TEst\opencv\node_modules\opencv
node-pre-gyp ERR! node -v v8.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node
_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --m
odule=E:\2TEst\opencv\node_modules\opencv\build\opencv\v6.0.0\Release\node-v57-w
in32-x64\opencv.node --module_name=opencv --module_path=E:\2TEst\opencv\node_mod
ules\opencv\build\opencv\v6.0.0\Release\node-v57-win32-x64' (1)
npm WARN enoent ENOENT: no such file or directory, open 'E:\2TEst\opencv\package
.json'
npm WARN opencv No description
npm WARN opencv No repository field.
npm WARN opencv No README data
npm WARN opencv No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2018-06-04T02_26_49_
790Z-debug.log
```

**Comment by pinxue** [comment]
@Aarul5 it seems you have not installed opencv yet. node-opencv doesn't include opencv itself.

**Comment by Aarul5** [comment]
@pinxue No i have installed opencv

```
C:\Users\admin>opencv_version
2.4.13.6

C:\Users\admin>
```
