### ISSUE TITLE
Not getting latest version?

### ISSUE THREAD

**Issue by eric-radiant** [peterbraden/node-opencv#551]
If I do ```npm install opencv``` I get an older version (6.0.0?) that is missing many functions from Matrix.cc . what do I need to do in order to get the latest?

**Comment by deify123** [comment]
The same thing happened to me, I managed to get the latest version by npm installing it from git directly [(https://stackoverflow.com/a/17509764).](https://stackoverflow.com/a/17509764) It should work if you put `"opencv": "git+https://git@github.com/peterbraden/node-opencv.git"` in your package.json and npm install afterwards.
