### ISSUE TITLE
Any plans for more Async functions?

### ISSUE THREAD

**Issue by btsimonh** [peterbraden/node-opencv#563]
I've done a number of updates, but based on the  master branch of https://github.com/akshonesports/node-opencv which has a load of modifications which I'm not sure of the reasons for.
On of the things I want/need is async functionality so that I can make best use of the 4 cores on an RPi3 (I have achieve 360% CPU in one nodejs (actually, node-red) process using async opencv resize...).
Should I start over based on this repo and provide PRs for my work?  akshonesports seems to be going in a different direction...
Any thoughts appreciated.

**Comment by peterbraden** [comment]
Definitely happy to take pull requests. The smaller the better as they're easier to review. Would love more async functions.

**Comment by btsimonh** [comment]
Q1: About style of making functions async;

For some, they already have callbacks (e.g. BackgroundSubtractor), and for these, I think adding a xxxSync function and converting the original function to async is best.
For other functions, (e.g. resize), I'd propose that if the first argument is a function, they it takes this as the callback, and the rest of the args remain unchanged.  e.g.
    img.resize({width:400, height:300});
becomes
    img.resize(function(err, newimage){ <do something> }, {width:400, height:300});
but can be used synchronous in it's original form?
Or would you rather have two distinct functions, one sync, and the other async?

And in terms of callbacks, to try to stick to fn(err, result), and wherever possible, callback with err rather than throw (I'm getting a lot of stone-dead nodejs crashes because of uncaught exceptions...).

Your thoughts on style are appreciated :).

**Comment by peterbraden** [comment]
The problem with converting the existing function to async is that it breaks the library users code, and imposes a maintenance burden on upgrading, so I'm kinda hesitant to recommend that, even though it's probably the cleanest solution.

Rather, and it's less pretty, but I'd think adding an additional xxxAsync function means that the library stays backwards compatible.

The callback style sounds good to me.

**Comment by btsimonh** [comment]
Where functions do not currently have a callback, the detection of the first arg as a function should avoid issues... so existing users code should be unaffected.
Where a function already has a callback, you are right; we could not predict if the user had accounted for the fn being called asynchronously; so either a new function, or a way of the fn operating as previously for existing user's code (e.g. in the case of backgroundsubtractor, moving the callback to the first arg of apply would make this detectable in code, and leave existing users synchronous).
Is the wiki & example the only documentation at the moment?

**Comment by mattlnl** [comment]
There exist a lib with async opencv nodejs function bindings. Not sure why they are different projects for node opencv.

**Comment by btsimonh** [comment]
@mattInl - can you point it out?  akshonesports has one or two (videocapture, mat.toBuffer), which is why I started there; 
https://github.com/macacajs/nodecv has some async; but not much functionality.
https://github.com/codeboost/opencv-node has less functionality..
https://github.com/justadudewhohacks/opencv4nodejs seems to have lots of functionality and a few async calls.
And that's where a github search runs out...

**Comment by mattlnl** [comment]
Sorry I mean opencv4nodejs. It seems to not exist so long yet
