### ISSUE TITLE
parsing jpeg buffer

### ISSUE THREAD

**Issue by btsimonh** [peterbraden/node-opencv#569]
Q: I can't find a function which parses a jpeg from a buffer (i.e. calls cv.imdecode?).
Is there one already, or should I add an API for imdecode?

**Comment by peterbraden** [comment]
If you don't see one, the chances are that it's not there.

**Comment by btsimonh** [comment]
Hi peter,
this is THE repo for opencv with node; but there are a number of others 'up and coming'.
Do you have a plan for this repo with respect to enhancing the implementation? - we created a wiki page highlighting contributions which would be desirable (i.e. people could add what they desire), where users/contributors could 'claim' updates on a date (which would give us an indication as to if they achieved it or not within a reasonable time) to minimise duplicated work.
I've got a vested interest - I don't want to change the interfaces I'm using :).
I'm promoting use of node-opencv in Node-Red (see https://btsimonh.wordpress.com/node-opencv-with-node-red/) and getting some interest....
let me know what you think?
s

**Comment by btsimonh** [comment]
new PR ready for you ref imdecode :).
s

**Comment by btsimonh** [comment]
hmm...  readImage actually does do it... but no async.  Sorry I didn't see it.  will think.
