### ISSUE TITLE
BackgroundSubtractor.applyMOG() - segmentation fault

### ISSUE THREAD

**Issue by MattCollins84** [peterbraden/node-opencv#581]
I am having a problem getting this to work - I see that there are some other issues opened but they seem to have died off so hoping for some more current information...

I am doing:

````javascript
const subtractor = new cv.BackgroundSubtractor();
subtractor.applyMOG(im, function(err, fgim) {
  // do some stuff
});
````

And I get: `Segmentation fault: 11`

- OpenCV `2.4.13.3`
- Node `8.4.0`
- NPM `5.3.0`

Has anyone got this working?

**Comment by btsimonh** [comment]
Hi Matt,

I have some PRs relating to backgroundsubtractor; still working on them, but so far so good.  
Only tested on OpenCV 3+ at the moment, but you can try them with
npm install btsimonh/node-opencv-nr#btsimonh-dev
It's basically the currentmaster branch plus the BG stuff...
Once we're more confident, we'll merge, so all feedback appreciated....
(it also adds async and allows MOG2 MOG and GMG if they are available; check the PR for operational details - not sure how up to date the text in the [PR](https://github.com/peterbraden/node-opencv/pull/576) is...)

to use async, 

```
const subtractor = new cv.BackgroundSubtractor();
subtractor.apply(im, function(err, fgim) {
  // do some stuff
});

```

to use 'new' sync:
```
const subtractor = new cv.BackgroundSubtractor();
var fgim = subtractor.apply(im);

```

original applyMOG is sync even though there is a callback.

s

**Comment by btsimonh** [comment]
you might like what [I've been doing:)](https://btsimonh.wordpress.com/node-opencv-with-node-red/)

**Comment by MattCollins84** [comment]
Wow that is very interesting, especially with node-red. I will show this to people in the office!

so, even on OpenCV 2 I can get `applyMOG()` to work. Going to try and figure out how to get MOG2 to play nice!

**Comment by btsimonh** [comment]
@MattCollins84 - all should be good from master now on this.  Note the changes to add a mutex into apply (the async version).
Re-open if you still have issues.
