### ISSUE TITLE
'toBuffer' function question.

### ISSUE THREAD

**Issue by programmerpsk** [peterbraden/node-opencv#582]
I used npm-opencv module in node.js and recently I write this code. (below);

#1. load image;

// skip this code.

#2. filtering image and save

// Variable declaration
var imgOutput = new cv.Matrix(width, height, cv.Constants.CV_8U);

/* skip this section of code (filtering) */

// and save it
imgOutput.save("public/img/output2.png");

So far, it works fine.

But What I want to do is rgb pixel data of result image(= imgeOutput);
so I use this fucntion 'toBuffer()' in npm-opencv.
(like this `imgOutput.toBuffer()`)

but `imgOutput.toBuffer()` data is not same what I thought..
I read image(16x16 pixels) so It's right length of pixels array is 1024.
but length of `imgOutput.toBuffer()` data is 529..

I misundertand 'toBuffer()' function???

How can I get pixel data in maxtrix image using npm-opencv functions.

**Comment by btsimonh** [comment]
toBuffer() is used to encode an image to a compressed format; it calls imencode() in opencv.
try getData().

**Comment by programmerpsk** [comment]
I use getData() function.
Then length of result array is 256 (pixel length of original image is 1024 in RGB map).
I think that this also seems to be compressed or color map formats is not RGB.
Do you know the color format result array of getData().

**Comment by btsimonh** [comment]
it seems to get the raw data from the mat.
above, you mention cv.Constants.CV_8U - is that not a monochrome 8 bit image type?
try CV_8UC3 for a 3 channel image.

**Comment by programmerpsk** [comment]
My mistake;
getData() is fine. result of length is 1024. (they have three channels. It's fine)
But their array values was different from pixel value in RGB map.

I saved the imgOutput(using imgOutput.save() function) and checked their pixel RGB values in photoshop program.
But their values was different from imgOutput.getData() values.

Why different?

**Comment by btsimonh** [comment]
if loading & saving in a compressed format, make sure it's lossless?

**Comment by btsimonh** [comment]
closing; please re-open if still an active issue...
