### ISSUE TITLE
Error: No rule to make target 'Release/obj.target/test_nativemat/test/nativemat.o'

### ISSUE THREAD

**Issue by ValkA** [peterbraden/node-opencv#591]
Hi,
Struggling this for a few days.
Running that inside a Docker container (Resin.IO) on a RaspberryPi3.
did the following:
`apt-get install libopencv-dev `
`npm install https://github.com/peterbraden/node-opencv`

Also tried compiling OpenCV from source (3 and 2.4) instead of running 
`apt-get install libopencv-dev`

Always `npm install https://github.com/peterbraden/node-opencv` giving the me same error:

CXX(target) Release/obj.target/opencv/src/Constants.o
CXX(target) Release/obj.target/opencv/src/Calib3D.o
CXX(target) Release/obj.target/opencv/src/ImgProc.o
CXX(target) Release/obj.target/opencv/src/Stereo.o
CXX(target) Release/obj.target/opencv/src/LDAWrap.o
CXX(target) Release/obj.target/opencv/src/Histogram.o
SOLINK_MODULE(target) Release/obj.target/opencv.node
COPY Release/opencv.node
COPY /usr/src/app/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-linux-arm/opencv.node
TOUCH Release/obj.target/action_after_build.stamp
make: *** No rule to make target 'Release/obj.target/test_nativemat/test/nativemat.o', needed by 'Release/obj.target/test_nativemat.node'.  Stop.
make: Leaving directory '/usr/src/app/node_modules/opencv/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/src/app/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.12.13
gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/node-gyp/bin/node-gyp.js" "build" "--build-from-source" "--module=/usr/src/app/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-linux-arm/opencv.node" "--module_name=opencv" "--module_path=/usr/src/app/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-linux-arm"
gyp ERR! cwd /usr/src/app/node_modules/opencv
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/src/app/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --module=/usr/src/app/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-linux-arm/opencv.node --module_name=opencv --module_path=/usr/src/app/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.12.13
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/.bin/node-pre-gyp" "install" "--build-from-source"
node-pre-gyp ERR! cwd /usr/src/app/node_modules/opencv
node-pre-gyp ERR! node -v v8.8.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/src/app/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --module=/usr/src/app/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-linux-arm/opencv.node --module_name=opencv --module_path=/usr/src/app/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-linux-arm' (1)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv@6.0.0 install: `node-pre-gyp install --build-from-source`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-15T07_51_33_620Z-debug.log

**Comment by ValkA** [comment]
BTW, installing with `npm install opencv` works but missing the VideoWriter object :(

**Comment by btsimonh** [comment]
that's a strange one.
However, did you try the result?  It built & copied the main library, and I'm not sure the native mat object is required except for running tests?  (that's if gyp didn't roll everything back on failure...).

For information/comparison only, my output of (native) RPi build using OpenCV 3.3.0 is here: https://gist.github.com/btsimonh/0ee84efedd3bb44273bc39cf67a7debb
The makefiles are built by gyp, so check your node/npm/gyp versions.
I've built this on node 8.9.0, 6.11.2; with OpenCV 3.0.0, 3.3.0.
The travis testing builds with OpenCV 2.4 on node 6.x and node 7.x

**Comment by btsimonh** [comment]
p.s. i would not recommend 8.9.0 - i'm only using it to diagnose some issues with buffers which I think changes in nodejs have caused.

**Comment by ValkA** [comment]
Thanks!
downgraded gyp with: `npm install -g node-gyp@3.4.0`, it didn't help.
changed to node 6.11.2 with: 
`npm install -g n`
`n 6.11.2`
And it compiled :)

(opencv was installed via `apt-get install libopencv-dev`)

**Comment by btsimonh** [comment]
for reference here, what nodejs version were you using?

**Comment by ValkA** [comment]
node -v v8.8.1
node-gyp -v v3.6.2

**Comment by dstarke** [comment]
In order to resolve this problem, I had to:
- update npm
- make sure that the install was not running under the root user
