### ISSUE TITLE
Problems loading PNG with alpha

### ISSUE THREAD

**Issue by Bellian** [peterbraden/node-opencv#596]
Hello,
I have a Problem loading a PNG images with alpha.
I will always get the error:
`Error: Image is no 3-channel
mainServer.ts:68 at cv.readImage (e:\SkodaImageMerger\src\webService\mainServer.ts:68:16)`

Is there a way to import the alpha channel or am I missing something?

**Comment by Bellian** [comment]
Never mind. I figured out the problem.. sorry to bother.

**Comment by Bellian** [comment]
Never mind. I figured out the problem.. sorry to bother.

**Comment by awaydian** [comment]
so whats the solution?
