### ISSUE TITLE
DOUBLE_FROM_ARGS forces all arguments to be integers

### ISSUE THREAD

**Issue by kubark42** [peterbraden/node-opencv#598]
```
#define DOUBLE_FROM_ARGS(NAME, IND) \
  if (info[IND]->IsInt32()){ \
    NAME = info[IND]->NumberValue(); \
  }
```

source: https://github.com/peterbraden/node-opencv/blob/ca7847d6518f6cf573ec9e714dd65f1cfad5ae9c/src/OpenCV.h#L79

If the input arguments are floating point, then this function will not assign them to the named value. 

Suggested fix: `IsInt32()` --> `IsNumber()`.

**Comment by marinoaldi** [comment]
I found the same problem and it's working after running your commit.
Could you submit a pull request to peterbraden repository to include it in master?
Thanks a lot

**Comment by kubark42** [comment]
@marinoaldi Glad it was helpful, I submitted a PR.
