### ISSUE TITLE
normalizing matrices does not work

### ISSUE THREAD

**Issue by deify123** [peterbraden/node-opencv#612]
When I try to normalize a matrix with the normalize function of [Matrix.cc](https://github.com/peterbraden/node-opencv/blob/48a4fc35e873f44cb0ee6004dae6bfa0c8157a31/src/Matrix.cc) I always get null returned, I tried it with a simple picture as well as with the matrix of eigenvectors returned by `facerec.getMat("eigenvectors");`(type is [ Matrix 10304x16 ]).
I even tried to create a mask and set all parameters like in [ node-opencv/examples/mat-normalize.js ](https://github.com/peterbraden/node-opencv/blob/33976a951a9a0bc86cfe34a5161c3ee6dc5cdc46/examples/mat-normalize.js) to no avail.

`cv.readImage("/path/to/test.jpg",function(err, img){`
`console.log("jpg: " + img.normalize(0,255));`
`});`
`console.log(eigenVectors.normalize(0,255)); `

I'm currently running node 6.12, opencv 3.2.0-13 as well as node-opencv 6.0.0 on Fedora.

**Comment by btsimonh** [comment]
hi deify123, the function does not return the image, it modifies the image you call against, and returns null.
i.e. 
eigenVectors.normalize(0,255)
console.log(eigenVectors);

**Comment by deify123** [comment]
Ahh ok, thanks for the quick answer 👍 .
It even says `info.GetReturnValue().Set(Nan::Null());` in the Matrix.cc but I didn't see the obvious :(
