### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by malpaniankit** [peterbraden/node-opencv#640]
Hi , I am trying to install this as node-red-contrib-opencv is dependent on it.  
I have already compiled and installed opencv which works well with Python3 , 

but when I am trying to install this node, I am unable to do it.  

Output of the terminal is -- 

> .node-red $ sudo npm install --unsafe-perm -g opencv
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.

>opencv@6.0.0 install /usr/lib/node_modules/opencv
node-pre-gyp install --fallback-to-build

>node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v67-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@11.2.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v67-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@11.2.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp)

followed by that there is a huge print of various warnings and errors and ultimately it fails  by displaying

> In file included from /root/.node-gyp/11.2.0/include/node/v8.h:26:0,
                 from ../src/OpenCV.h:14,
                 from ../src/Contours.h:1,
                 from ../src/Matrix.cc:1:
/root/.node-gyp/11.2.0/include/node/v8.h:2571:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/11.2.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Matrix.cc:2609:65: error: no matching function for call to ‘v8::Function::NewInstance()’
       Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                 ^
In file included from ../src/OpenCV.h:14:0,
                 from ../src/Contours.h:1,
                 from ../src/Matrix.cc:1:
/root/.node-gyp/11.2.0/include/node/v8.h:4105:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/root/.node-gyp/11.2.0/include/node/v8.h:4105:44: note:   candidate expects 3 arguments, 0 provided
/root/.node-gyp/11.2.0/include/node/v8.h:4108:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/root/.node-gyp/11.2.0/include/node/v8.h:4108:44: note:   candidate expects 1 argument, 0 provided
../src/Matrix.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Matrix::Subtract(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Matrix.cc:2633:69: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   Matrix *other = Nan::ObjectWrap::Unwrap<Matrix>(info[0]->ToObject());
                                                                     ^
In file included from ../src/OpenCV.h:14:0,
                 from ../src/Contours.h:1,
                 from ../src/Matrix.cc:1:
/root/.node-gyp/11.2.0/include/node/v8.h:10254:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
opencv.target.mk:122: recipe for target 'Release/obj.target/opencv/src/Matrix.o' failed
make: *** [Release/obj.target/opencv/src/Matrix.o] Error 1
make: Leaving directory '/usr/lib/node_modules/opencv/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/opencv/build/opencv/v6.0.0/Release/node-v67-linux-arm/opencv.node" "--module_name=opencv" "--module_path=/usr/lib/node_modules/opencv/build/opencv/v6.0.0/Release/node-v67-linux-arm"
gyp ERR! cwd /usr/lib/node_modules/opencv
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/opencv/build/opencv/v6.0.0/Release/node-v67-linux-arm/opencv.node --module_name=opencv --module_path=/usr/lib/node_modules/opencv/build/opencv/v6.0.0/Release/node-v67-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Linux 4.14.79-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/opencv
node-pre-gyp ERR! node -v v11.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/opencv/build/opencv/v6.0.0/Release/node-v67-linux-arm/opencv.node --module_name=opencv --module_path=/usr/lib/node_modules/opencv/build/opencv/v6.0.0/Release/node-v67-linux-arm' (1)
opencv.target.mk:122: recipe for target 'Release/obj.target/opencv/src/Matrix.o' failed
make: *** [Release/obj.target/opencv/src/Matrix.o] Error 1
make: Leaving directory '/usr/lib/node_modules/opencv/build'
gyp ERR! build error | install: info lifecycle opencv@6.0.0~install: Failed to exec install script
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/opencv/build/opencv/v6.0.0/Release/node-v67-linux-arm/opencv.node" "--module_name=opencv" "--module_path=/usr/lib/node_modules/opencv/build/opencv/v6.0.0/Release/node-v67-linux-arm"
gyp ERR! cwd /usr/lib/node_modules/opencv
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN opencv@6.0.0 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-20T11_05_29_716Z-debug.log

> 

Please help me out here on getting started with OPENCV on NOde-red ,   

thanks in advance

**Comment by strarsis** [comment]
Still having this issue on WSL 1 (Bash on Windows).
