### ISSUE TITLE
[BUG]not a function 

### ISSUE THREAD

**Issue by nickabocker171** [peterbraden/node-opencv#664]
**Describe the bug**
Trying to use OpenCV function ImageSimilarity but receive an error each time I run NPM start.
**To Reproduce**
https://www.twilio.com/wireless/blueprints/security-camera/steps/6

Above link is steps involved for project I was testing. Package.json references NPM install opencv

**OS / Libraries**
- Operating System - raspberian buster
- OpenCV Version -latest
- ONLY CREATE IF YOU ARE USING THE LATEST VERSION OF NODE-OPENCV

**Additional context**

**Comment by guangmingwan** [comment]
Run node-v in Bash to confirm the version of nodejs. If it is less than 12, it can be used. If the version of nodejs is greater than 12, try the version I modified:
Https://gitee.com/netwan/node-opencv     (nodejs12+ supported)

**Comment by peterbraden** [comment]
Can you make a pull request?

**Comment by peterbraden** [comment]
Fixed in #667
