### ISSUE TITLE
Is it possible to limit the VideoStream frame rate?

### ISSUE THREAD

**Issue by ajfisher** [peterbraden/node-opencv#67]
I've got an application where I want to have a relatively low framerate. The reason for this is that I have a video stream being supplied by a camera attached to a robot. The robot core uses a Raspberry Pi and is using node-opencv to process the data which is then served to the client.

The issue I have it that an RPI is an incredibly lightweight system and processing the video is consuming 98% of CPU cycles. I have this code doing the very basic processing:

``` javascript

video_stream.on('data', function(matrix){
    var curtime = Date.now();
     if (curtime > (last_frame + capture_fps)) {
          matrix.convertGrayscale();
          matrix.pyrDown();
          video_buffer = matrix.toBuffer();
          last_frame = curtime;
      }                                                                   
});  

```

So theoretically I'm limiting the processing of the video to whatever my framerate is (1s in this case) so I'm using less processing there when I need to do the work to resize it, greyscale it and then put it into a buffer for sending. So that's ace.

But what appears to be the case is that because the video stream is in fact a stream, the "data" event is firing at about 20fps which appears to be maxing the CPU as it attempts to process all those frames, even though I'm essentially discarding them.

So why don't I run at full tilt?

Because I need to transmit all that data and also because the video stream is flooding the CPU there's appreciable lag (1-2 seconds min) in the stream and also the robot needs to do other things, when the robot starts working then you notice the lag goes up to 3-4 seconds.

So ideally I'd just like to drop the originating frame rate to about 3fps which is plenty enough for a slow moving robot to go with.

Any thoughts?

**Comment by danschultzer** [comment]
This is more than 2 years old, with no follow up from @ajfisher. I guess this is no longer relevant, but please reply if there's still issues.
