### ISSUE TITLE
[BUG] OpenCV Not Working on MacOS Big Sur 11.6.4

### ISSUE THREAD

**Issue by danilo-dsf** [peterbraden/node-opencv#684]
**Describe the bug**
Hi guys,

I'm having an issue with opencv lib on my MacOS Big Sur 11.6.4.

I followed the installation instructions and it did not work for me.
I mean, the opencv installation had no errors, but when I tried to run a simple nodejs project with the lib installed, I received the error below.

Does anyone know how to fix this?

The simple nodejs project I used can be found here: https://github.com/danilo-dsf/test-opencv

**To Reproduce**
```shell
$ brew install pkg-config

$ brew install opencv@2

$ brew link --force opencv@2

$ mkdir test-opencv

$ cd test-opencv

$ yarn init -y

$ yarn add opencv

$ touch server.js

$ nano server.js - (Write a simple console log and import. the opencv lib)

$ node server.js
```

**Expected behavior**
Expected tho work fine.

**Screenshots**
https://imgur.com/iuSyq0y.png

**OS / Libraries**
- MacOS Big Sur 11.6.4
- opencv@2 / opencv ^7.0.0

**Comment by mok419** [comment]
hoping it works :)), other people reported issues with newer versions of node aswell. :((
