### ISSUE TITLE
Error on npm install: "Package 'opencv' has no Name: field"

### ISSUE THREAD

**Issue by Talamantez** [peterbraden/node-opencv#75]
Hi All - very excited about using opencv with node, but I'm getting an install error:

os: windows 7
terminal: cygwin

error: 
<code>
C:\Users\rtalaman\AppData\Roaming\npm\node_modules\opencv>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean rebuild
<strong>Package 'opencv' has no Name: field</strong>
gyp: Call to 'pkg-config --cflags "opencv >= 2.3.1"' returned exit status 1. while trying to load binding.gyp
npm ERR! opencv@0.3.1 preinstall: `node-gyp clean rebuild`
npm ERR! `cmd "/c" "node-gyp clean rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the opencv@0.3.1 preinstall script.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp clean rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "opencv"
npm ERR! cwd C:\cygwin\home\rtalaman
npm ERR! node -v v0.8.17
npm ERR! npm -v 1.2.0
npm ERR! code ELIFECYCLE
</code>

I checked out the github and the manifest indeed has a Name, so I'm not sure what could be throwing this error. Any help is appreciated.
Thanks - Robert

**Comment by danschultzer** [comment]
Installing newer version of node and npm should fix this.
