### ISSUE TITLE
Error in installing node open cv in windows

### ISSUE THREAD

**Issue by subhendusc** [peterbraden/node-opencv#83]
Can you please help me with the installation of node opencv
I have opencv installed which I can access from python. It is in d:\opencv
When I try to issue the command c:\npm install opencv  I get errors which is given below
 
 
C:\>npm install opencv
npm WARN package.json webcam-parallax@0.0.0 No repository field.
npm WARN package.json webcam-parallax@0.0.0 No readme data.
npm http GET https://registry.npmjs.org/opencv
npm http 304 https://registry.npmjs.org/opencv
npm WARN package.json opencv@0.3.1 No repository field.
 
> opencv@0.3.1 preinstall C:\node_modules\opencv
> node-gyp clean rebuild
 
 
C:\node_modules\opencv>node "C:\Program Files\nodejs\node_modules\npm\bin\node-g
yp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean rebuild
'pkg-config' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'pkg-config --cflags "opencv >= 2.3.1"' returned exit status 1. whi
le trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:415:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "clean" "rebuild"
gyp ERR! cwd C:\node_modules\opencv
gyp ERR! node -v v0.10.7
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0

Open cv is working fine with python

**Comment by guywithcrookedface** [comment]
Same thing here, this is going to be a show-stopper.

**Comment by brianofrokk3r** [comment]
Same issue as @subhendusc

**Comment by funky81** [comment]
Hi @seyedaed ....

Thanks for guidance. I have successfully install node-opencv over my windows 10
following is my walk-through to install this

1. Download Install opencv @ - (I used version 2.4.4)
http://opencv.org/downloads.html
Put it in c:\opencv

2. Install python version 2.7 @
http://www.python.org/download/releases/2.7/
put it in c:\python27

3. install pkg-config by downloading the all in one bundle @ - (I used Gtk+ 3.6.4)
http://www.gtk.org/download/win64.php
put it in c:\pkg-config

4. Add the following to your path variables
C:\pkg-config\bin;C:\OpenCV\build\x64\vc11\bin;

5. Install visual-studio in 4 steps
- First install Visual C++ 2010 Express
- Second install Windows SDK for windows 7 and .net framework 4
- Third install Visual Studio 2010 Service Pack 1 
- Fourth install Visual C++ 2010 Service Pack 1 Compiler

6. Download npeterbraden/node-opencv fork
git clone https://github.com/peterbraden/node-opencv

7. edit file src/Matrix.cpp
put "inline double round( double d ) { return floor( d + 0.5);}" below "cv::Rect* setRect(Local<Object> objRect, cv::Rect &result);"

8. run npm install
