### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Talamantez** [peterbraden/node-opencv#86]
Hi. I am getting the following error on npm install. What do you think could be causing it? Thanks.

<code> opencv_manual.cpp
..\src\opencv_manual.cpp(1): fatal error C1083: Cannot open include file: 'cv.hpp': No such file or directory [C:\Users\rtalaman\AppData\Roaming\npm\node_modules\opencv-node\build\addon.vcxproj]
  addon.cpp
c:\users\rtalaman\appdata\roaming\npm\node_modules\opencv-node\src\opencvjs.h(5): fatal error C1083: Cannot open include file: 'cv.hpp': No such file or directory (..\src\opencvjs.cpp) [C:\Users\rtalaman\AppData\Roaming\npm\node_modules\opencv-node\build\addon.vcxproj]
c:\users\rtalaman\appdata\roaming\npm\node_modules\opencv-node\src\opencvjs.h(5): fatal error C1083: Cannot open include file: 'cv.hpp': No such file or directory (..\src\addon.cpp) [C:\Users\rtalaman\AppData\Roaming\npm\node_modules\opencv-node\build\addon.vcxproj]
</code>

**Comment by danschultzer** [comment]
This is an outdated issue, and I guess it's no longer relevant. I'll close it.
