### ISSUE TITLE
Cannot get video input to work

### ISSUE THREAD

**Issue by mattsoftware** [peterbraden/node-opencv#88]
Hi. I'm not experienced with opencv (althought I've looked at it in the past, but it looks a lot more complete now) but have decided to use node to have a good look at opencv and see what it can do for me.

I am having no end of trouble trying to get it to work on my macbook. Although I believe everything is installed and setup correctly (i can run the 'npm test opencv' without errors) and some of the examples work (addweighted.js, color_filter.js, contours.js, convert_image.js, detect_shapes.js, face.js, face_detect.js, quad-crosses.js). But it appears that any code even thinking of touching my eyesight camera (or even a second webcam plugged into usb) just fails miserably. 

Due to a lack of documentation, and experience with opencv, I am at a loss of where to start to debug. Is the node-opencv wrapper not working? Is the opencv binaries not installed correctly? 

If anyone can help me with this I would greatly appreciate it. I am happy to fix code and contribute examples, documentation, but I would like to get a better understanding on what I am doing first.

Thank You.
Matt.

P.S. Just for completeness I will highlight the examples below that I have had issues with...

```
=====8<-----
camera.js - All I get are the following errors every second...

libpng warning: Image width is zero in IHDR
libpng warning: Image height is zero in IHDR
libpng error: Invalid IHDR data
libpng warning: Image width is zero in IHDR
libpng warning: Image height is zero in IHDR
libpng error: Invalid IHDR data
(etc)

=====8<-----
face-proxy.js - Working out how to run this might have tripped a few newbies up, but after finding a successful image online to find....

				im.faceDetect(im, {}, function(err, faces) {
				   ^
TypeError: Object #<Matrix> has no method 'faceDetect'

=====8<-----
motion-track.js - After running this is echo'ed on the console...

motion-track.js:355: Uncaught TypeError: track takes an image param

=====8<-----
salt.js - seg fault :/

Segmentation fault: 11

=====8<-----
take-face-pics.js - Errors out...

OpenCV Error: Bad flag (parameter or structure field) (Unrecognized or unsupported array type) in cvGetMat, file /tmp/opencv-bVUq/opencv-2.4.6.1/modules/core/src/array.cpp, line 2482
libc++abi.dylib: terminate called throwing an exception
Abort trap: 6


````

**Comment by danschultzer** [comment]
Some of these errors are self explanatory. E.g. there's no `faceDetect` method on the matrix object. Not sure if this was just buggy code from an early release of `opencv`.

However, since this issue is more than two years old, I'll close it for now. Please reply if you still having trouble with `opencv@5.0.0`.
