### ISSUE TITLE
FaceRecognizer

### ISSUE THREAD

**Issue by agustinhaller** [peterbraden/node-opencv#92]
Hi, does this library support opencv FaceRecognizer?

I mean, i need to use the method "createLBPHFaceRecognizer". I want to something like this

``` c
Ptr<FaceRecognizer> model = createLBPHFaceRecognizer();
model->train(images, labels);
// The following line predicts the label of a given
// test image:
int predictedLabel = model->predict(testSample);
```

I notice in the file FaceRecognizer.cc theres a reference to that

``` c
NODE_SET_METHOD(constructor, "createLBPHFaceRecognizer", CreateLBPH);
```

But i don't know how to use it from node. Any help is appreciated!

**Comment by mazki516** [comment]
+1 +1 +1 +1
