### ISSUE TITLE
Error loading file at Matrix.matrix.detectObject

### ISSUE THREAD

**Issue by agustinhaller** [peterbraden/node-opencv#93]
Hi, i'm trying to run the examples, but i'm getting some errors when running the face_detection.js file.

Here's what i get:

``` bash
MacBook-Pro-de-Agustin:examples agustinhaller$ node face_detection.js

/Users/agustinhaller/repos/nodecv.com/node_modules/opencv/lib/opencv.js:29
      var face_cascade = new cv.CascadeClassifier(classifier);
                         ^
TypeError: Error loading file
    at Matrix.matrix.detectObject (/Users/agustinhaller/repos/nodecv.com/node_modules/opencv/lib/opencv.js:29:23)
    at /Users/agustinhaller/repos/nodecv.com/node_modules/opencv/examples/face_detection.js:9:9
    at Object.<anonymous> (/Users/agustinhaller/repos/nodecv.com/node_modules/opencv/examples/face_detection.js:7:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

```

I'm very new to this, so i don't have much idea which may be the problem. Any help is appreciated!

**Comment by oddityoverseer13** [comment]
@agustinhaller I'm also seeing this error. The fix @gossamershadow gave didn't resolve the issue for me. Could you clarify what you did to fix your issue?

**Comment by oddityoverseer13** [comment]
lol I guess I'll follow the trend. I fixed my issue on my own as well. Instead of doing this:
```
var cascade = new opencv.CascadeClassifier("./cascades/hogcascade_cars_sideview.xml");
```

I gave the filename directly to detectObject:
```
im.detectObject("./cascades/new_cascade.xml", {}, function(err, detections){
```

**Comment by AVVS** [comment]
that works, or you can do `path.resolve(__dirname, 'relative/path/to/classifier.xml')`

**Comment by oddityoverseer13** [comment]
hmm..will that allow me to load a cascade once, and use it in multiple detect statements?

**Comment by AVVS** [comment]
cascades are cached once they are resolved, so it doesn't matter which way you use

**Comment by oddityoverseer13** [comment]
Ok, so if I do something like this:
```
images.each(function(img){
   img.detectObject("../cascades/hogcascade_cars_sideview.xml", {}, function(err, detections){
   ...
   })
})
```
It'll only load that cascade once?

**Comment by AVVS** [comment]
Yes, it will only read file once

https://github.com/peterbraden/node-opencv/blob/master/lib/opencv.js#L16-L28

However, note that after that operation is async, and if you want to track progress use bluebird or async or neo-async, or whatever you prefer for flow control

**Comment by oddityoverseer13** [comment]
Ok. I'm still having issues, but I'm gonna open another issue, because at this point it's unrelated.
