### ISSUE TITLE
FaceRecognizer.h guard not specific enough

### ISSUE THREAD

**Issue by loganfsmyth** [peterbraden/node-opencv#96]
The include guard for `FaceRecognizer.h` is:

    #if CV_MAJOR_VERSION >= 2 && CV_MINOR_VERSION >=4

however this module makes use of

    createLBPHFaceRecognizer(1, 8, 8, 8, 80.0);

The 5-argument version of `createLBPHFaceRecognizer` was not introduced until 2.4.3, so it is currently not possible to compile this library on 2.4.0. There appear to be a few other compiler errors too.

I just ran across this on StackOverflow, so sorry I can't help more. http://stackoverflow.com/questions/20911654/gyp-errors-when-trying-to-install-opencv-node-on-mac-mavericks-trouble/20914153?noredirect=1#comment31417777_20914153

**Comment by danschultzer** [comment]
This has been fixed with https://github.com/peterbraden/node-opencv/pull/379
