### ISSUE TITLE
delete camera does not stop camera, camera is still on

### ISSUE THREAD

**Issue by ghost** [peterbraden/node-opencv#99]
i am using
var camera = new cv.VideoCapture(0);

i read N  images from camera, then i want to stop camera, so i am doing "delete camera", but no luck, camera is still on  and when some other app try to access camera it says busy and that app is crashed.

so, is there a mechanism for me to stop the camera after my usage is done ?

Thanks

**Comment by danschultzer** [comment]
You can call `camera.close()`, to close the stream. I've [added a PR](#444) to rename it to `.release`.
